// Generated by Code Factory
// Spec: SPEC-20260319-005
// Date: 2026-03-19
// DO NOT EDIT

/**
 * Tests for GET /api/lessons and GET /api/lessons/:id
 * Database is mocked; no live PostgreSQL required.
 */

import request from 'supertest';

// ─── Mock DB ──────────────────────────────────────────────────────────────────
const mockQuery = jest.fn();

jest.mock('../../db.js', () => ({
  __esModule: true,
  default: { query: jest.fn(), end: jest.fn() },
  query: (...args: unknown[]) => mockQuery(...args),
  getClient: jest.fn(),
  closePool: jest.fn().mockResolvedValue(undefined),
}));

import { app } from '../../index.js';

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const unitRow = {
  id: 1,
  type: 'letter',
  characters: 'a',
  display_name: 'Letter A',
  audio_file: 'phoneme-a.mp3',
  order_index: 1,
  created_at: new Date('2026-01-01T00:00:00Z'),
};

const wordRow = {
  id: 1,
  unit_id: 1,
  word: 'apple',
  image_file: 'img-apple.png',
  audio_file: 'word-apple.mp3',
  created_at: new Date('2026-01-01T00:00:00Z'),
};

beforeEach(() => {
  mockQuery.mockReset();
});

// ─── GET /api/lessons ─────────────────────────────────────────────────────────

describe('GET /api/lessons', () => {
  it('returns 200 with a list of units', async () => {
    mockQuery.mockResolvedValueOnce([unitRow]);

    const res = await request(app).get('/api/lessons');

    expect(res.status).toBe(200);
    expect(res.body.status).toBe('ok');
    expect(Array.isArray(res.body.data)).toBe(true);
    expect(res.body.data).toHaveLength(1);
  });

  it('maps snake_case DB columns to camelCase interface', async () => {
    mockQuery.mockResolvedValueOnce([unitRow]);

    const res = await request(app).get('/api/lessons');
    const unit = res.body.data[0] as Record<string, unknown>;

    expect(unit['id']).toBe(1);
    expect(unit['characters']).toBe('a');
    expect(unit['displayName']).toBe('Letter A');
    expect(unit['audioFile']).toBe('phoneme-a.mp3');
    expect(unit['orderIndex']).toBe(1);
  });

  it('returns 200 with an empty array when no units exist', async () => {
    mockQuery.mockResolvedValueOnce([]);

    const res = await request(app).get('/api/lessons');

    expect(res.status).toBe(200);
    expect(res.body.data).toEqual([]);
    expect(res.body.error).toBeNull();
  });

  it('returns 500 when the database throws', async () => {
    mockQuery.mockRejectedValueOnce(new Error('connection refused'));

    const res = await request(app).get('/api/lessons');

    expect(res.status).toBe(500);
    expect(res.body.status).toBe('error');
    expect(res.body.error).toBe('connection refused');
  });
});

// ─── GET /api/lessons/:id ─────────────────────────────────────────────────────

describe('GET /api/lessons/:id', () => {
  it('returns 200 with unit and words for a valid id', async () => {
    mockQuery
      .mockResolvedValueOnce([unitRow])  // first call: fetch unit
      .mockResolvedValueOnce([wordRow]); // second call: fetch words

    const res = await request(app).get('/api/lessons/1');

    expect(res.status).toBe(200);
    expect(res.body.status).toBe('ok');
    expect(res.body.data.unit).toBeDefined();
    expect(res.body.data.words).toBeDefined();
  });

  it('returns the unit with correctly mapped fields', async () => {
    mockQuery
      .mockResolvedValueOnce([unitRow])
      .mockResolvedValueOnce([wordRow]);

    const res = await request(app).get('/api/lessons/1');
    const unit = res.body.data.unit as Record<string, unknown>;

    expect(unit['id']).toBe(1);
    expect(unit['type']).toBe('letter');
    expect(unit['displayName']).toBe('Letter A');
    expect(Array.isArray(res.body.data.words)).toBe(true);
    expect((res.body.data.words as unknown[]).length).toBe(1);
  });

  it('returns 404 when the unit does not exist', async () => {
    mockQuery.mockResolvedValueOnce([]); // unit not found

    const res = await request(app).get('/api/lessons/9999');

    expect(res.status).toBe(404);
    expect(res.body.status).toBe('error');
    expect(res.body.error).toBe('Lesson not found');
    expect(res.body.data).toBeNull();
  });

  it('returns 404 for a non-numeric id', async () => {
    const res = await request(app).get('/api/lessons/abc');

    expect(res.status).toBe(404);
    expect(res.body.status).toBe('error');
    expect(res.body.data).toBeNull();
  });

  it('returns 500 when the database throws on unit fetch', async () => {
    mockQuery.mockRejectedValueOnce(new Error('timeout'));

    const res = await request(app).get('/api/lessons/1');

    expect(res.status).toBe(500);
    expect(res.body.status).toBe('error');
    expect(res.body.error).toBe('timeout');
  });
});
