// Generated by Code Factory
// Spec: SPEC-20260319-006
// Date: 2026-03-19
// DO NOT EDIT

import request from 'supertest';
import app from '../../index.js';

describe('Progress Routes', () => {
  describe('GET /api/progress/:userId', () => {
    test('returns 200 with empty array for new user', async () => {
      const res = await request(app).get('/api/progress/9999');
      expect(res.status).toBe(200);
      expect(res.body.status).toBe('ok');
      expect(Array.isArray(res.body.data)).toBe(true);
    });

    test('returns 400 for invalid userId', async () => {
      const res = await request(app).get('/api/progress/invalid');
      expect(res.status).toBe(400);
      expect(res.body.status).toBe('error');
      expect(res.body.error).toContain('Invalid');
    });
  });

  describe('POST /api/progress/:userId/unit/:unitId', () => {
    test('returns 200 and creates progress record', async () => {
      const res = await request(app)
        .post('/api/progress/1/unit/1')
        .send({ completed: true, score: 85 });

      expect(res.status).toBe(200);
      expect(res.body.status).toBe('ok');
      expect(res.body.data.userId).toBe(1);
      expect(res.body.data.unitId).toBe(1);
      expect(res.body.data.score).toBe(85);
      expect(res.body.data.completed).toBe(true);
    });

    test('returns 404 for nonexistent unit', async () => {
      const res = await request(app)
        .post('/api/progress/1/unit/99999')
        .send({ completed: true, score: 50 });

      expect(res.status).toBe(404);
      expect(res.body.status).toBe('error');
      expect(res.body.error).toContain('not found');
    });

    test('returns 400 for invalid score', async () => {
      const res = await request(app)
        .post('/api/progress/1/unit/1')
        .send({ completed: true, score: 150 });

      expect(res.status).toBe(400);
      expect(res.body.status).toBe('error');
      expect(res.body.error).toContain('score');
    });

    test('returns 400 for missing body fields', async () => {
      const res = await request(app)
        .post('/api/progress/1/unit/1')
        .send({ completed: true });

      expect(res.status).toBe(400);
      expect(res.body.status).toBe('error');
    });
  });
});
