// Generated by Code Factory | Spec: SPEC-20260319-007 | Date: 2026-03-19
// DO NOT EDIT

import { Stack } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { Colors } from '../constants/theme';

/**
 * Root layout for the Phonics App.
 * Uses Expo Router Stack navigator with named screens:
 *   - index       → Home screen (lesson list)
 *   - lesson/[id] → Lesson detail
 *   - progress    → User progress + badges
 */
export default function RootLayout(): JSX.Element {
  return (
    <>
      <StatusBar style="light" />
      <Stack
        screenOptions={{
          headerStyle: {
            backgroundColor: Colors.primary,
          },
          headerTintColor: Colors.white,
          headerTitleStyle: {
            fontWeight: '700',
            fontSize: 20,
          },
          contentStyle: {
            backgroundColor: Colors.background,
          },
          animation: 'slide_from_right',
        }}
      >
        <Stack.Screen
          name="index"
          options={{
            title: 'Phonics Lessons',
            headerRight: undefined,
          }}
        />
        <Stack.Screen
          name="lesson/[id]"
          options={{
            title: 'Lesson',
            headerBackTitle: 'Back',
          }}
        />
        <Stack.Screen
          name="progress"
          options={{
            title: 'My Progress',
            headerBackTitle: 'Back',
          }}
        />
      </Stack>
    </>
  );
}
