// Generated by Code Factory | Spec: SPEC-20260319-008 | Date: 2026-03-19
// DO NOT EDIT

import React, { useCallback } from 'react';
import {
  View,
  Text,
  FlatList,
  ActivityIndicator,
  TouchableOpacity,
  StyleSheet,
  ListRenderItemInfo,
} from 'react-native';
import { useRouter } from 'expo-router';
import type { Lesson } from '@phonics-app/shared';
import { LessonCard } from '../components/LessonCard';
import { useLessonList } from '../hooks/useLesson';
import { Colors, Typography, Spacing, FontWeight, BorderRadius } from '../constants/theme';

// ─── Component ────────────────────────────────────────────────────────────────

export default function HomeScreen(): JSX.Element {
  const router = useRouter();
  const { lessons, isLoading, error, refresh } = useLessonList();

  const handleLessonPress = useCallback(
    (lessonId: number) => {
      router.push(`/lesson/${lessonId}`);
    },
    [router],
  );

  const renderItem = useCallback(
    ({ item }: ListRenderItemInfo<Lesson>) => (
      <LessonCard lesson={item} onPress={handleLessonPress} />
    ),
    [handleLessonPress],
  );

  const keyExtractor = useCallback((item: Lesson) => String(item.id), []);

  const renderEmpty = useCallback(() => {
    if (isLoading) return null;
    return (
      <View style={styles.emptyContainer}>
        <Text style={styles.emptyText}>No lessons available.</Text>
        <TouchableOpacity onPress={refresh} style={styles.retryButton}>
          <Text style={styles.retryText}>Refresh</Text>
        </TouchableOpacity>
      </View>
    );
  }, [isLoading, refresh]);

  if (error !== null) {
    return (
      <View style={styles.centered}>
        <Text style={styles.errorText}>{error}</Text>
        <TouchableOpacity onPress={refresh} style={styles.retryButton} testID="retry-button">
          <Text style={styles.retryText}>Try Again</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (isLoading && lessons.length === 0) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={Colors.primary} testID="loading-indicator" />
        <Text style={styles.loadingText}>Loading lessons…</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <FlatList<Lesson>
        data={lessons}
        renderItem={renderItem}
        keyExtractor={keyExtractor}
        ListEmptyComponent={renderEmpty}
        contentContainerStyle={styles.listContent}
        showsVerticalScrollIndicator={false}
        onRefresh={refresh}
        refreshing={isLoading}
        testID="lessons-list"
      />
      <TouchableOpacity
        style={styles.progressButton}
        onPress={() => router.push('/progress')}
        accessibilityLabel="View my progress"
        testID="progress-button"
      >
        <Text style={styles.progressButtonText}>My Progress →</Text>
      </TouchableOpacity>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  listContent: {
    paddingTop: Spacing.sm,
    paddingBottom: Spacing.xxl,
  },
  emptyContainer: {
    padding: Spacing.lg,
    alignItems: 'center',
  },
  emptyText: {
    ...Typography.md,
    color: Colors.textMuted,
    marginBottom: Spacing.sm,
  },
  loadingText: {
    ...Typography.md,
    color: Colors.textMuted,
    marginTop: Spacing.sm,
  },
  errorText: {
    ...Typography.md,
    color: Colors.error,
    textAlign: 'center',
    marginBottom: Spacing.sm,
  },
  retryButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  retryText: {
    ...Typography.md,
    color: Colors.white,
    fontWeight: FontWeight.semiBold,
  },
  progressButton: {
    position: 'absolute',
    bottom: Spacing.lg,
    right: Spacing.sm,
    backgroundColor: Colors.secondary,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
  },
  progressButtonText: {
    ...Typography.md,
    color: Colors.white,
    fontWeight: FontWeight.bold,
  },
});
