// Generated by Code Factory | Spec: SPEC-20260319-011 | Date: 2026-03-19
// DO NOT EDIT

import React, { useCallback } from 'react';
import {
  View,
  Text,
  ScrollView,
  FlatList,
  ActivityIndicator,
  TouchableOpacity,
  StyleSheet,
  ListRenderItemInfo,
} from 'react-native';
import { useRouter } from 'expo-router';
import type { UserProgress } from '@phonics-app/shared';
import { ProgressBadge } from '../components/ProgressBadge';
import { useProgress } from '../hooks/useProgress';
import { Colors, Typography, Spacing, FontWeight, BorderRadius, Shadow } from '../constants/theme';

// ─── Constants ────────────────────────────────────────────────────────────────

/** Hardcoded for MVP — would come from auth context in prod */
const MOCK_USER_ID = 1;

/** Placeholder unit name map — in prod, fetch from /api/lessons or pass via nav params */
const UNIT_NAME_MAP: Record<number, string> = {};

function getUnitName(unitId: number): string {
  return UNIT_NAME_MAP[unitId] ?? `Unit ${unitId}`;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function ProgressScreen(): JSX.Element {
  const router = useRouter();
  const { progress, stats, isLoading, error, refresh } = useProgress(MOCK_USER_ID);

  const handleBadgePress = useCallback(
    (unitId: number) => {
      // Navigate to the first lesson of this unit
      router.push(`/lesson/${unitId}`);
    },
    [router],
  );

  const renderBadge = useCallback(
    ({ item }: ListRenderItemInfo<UserProgress>) => (
      <ProgressBadge
        progress={item}
        unitName={getUnitName(item.unitId)}
        onPress={handleBadgePress}
      />
    ),
    [handleBadgePress],
  );

  const keyExtractor = useCallback((item: UserProgress) => String(item.unitId), []);

  if (error !== null) {
    return (
      <View style={styles.centered}>
        <Text style={styles.errorText}>{error}</Text>
        <TouchableOpacity onPress={refresh} style={styles.retryButton} testID="retry-button">
          <Text style={styles.retryText}>Try Again</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (isLoading && progress.length === 0) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={Colors.primary} testID="loading-indicator" />
        <Text style={styles.loadingText}>Loading progress…</Text>
      </View>
    );
  }

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
      testID="progress-scroll"
    >
      {/* Stats summary card */}
      <View style={styles.statsCard} testID="stats-card">
        <Text style={styles.statsHeading}>Your Progress</Text>
        <View style={styles.statsRow}>
          <StatBlock label="Completed" value={`${stats.completedUnits}/${stats.totalUnits}`} />
          <StatBlock label="Avg Score" value={`${stats.averageScore}%`} />
          <StatBlock label="Complete" value={`${stats.completionPercent}%`} />
        </View>
        {/* Progress bar */}
        <View style={styles.progressBarTrack}>
          <View
            style={[styles.progressBarFill, { width: `${stats.completionPercent}%` }]}
            testID="progress-bar"
          />
        </View>
      </View>

      {/* Badge grid */}
      <Text style={styles.sectionHeading}>Units</Text>
      {progress.length === 0 ? (
        <View style={styles.emptyContainer} testID="empty-state">
          <Text style={styles.emptyText}>No progress yet. Start a lesson!</Text>
        </View>
      ) : (
        <FlatList<UserProgress>
          data={progress}
          renderItem={renderBadge}
          keyExtractor={keyExtractor}
          numColumns={2}
          columnWrapperStyle={styles.badgeRow}
          scrollEnabled={false}
          contentContainerStyle={styles.badgeGrid}
          onRefresh={refresh}
          refreshing={isLoading}
          testID="badges-list"
        />
      )}
    </ScrollView>
  );
}

// ─── StatBlock sub-component ─────────────────────────────────────────────────

interface StatBlockProps {
  label: string;
  value: string;
}

function StatBlock({ label, value }: StatBlockProps): JSX.Element {
  return (
    <View style={styles.statBlock}>
      <Text style={styles.statValue}>{value}</Text>
      <Text style={styles.statLabel}>{label}</Text>
    </View>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    padding: Spacing.sm,
    paddingBottom: Spacing.xxl,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  statsCard: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.xl,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    ...Shadow.md,
  },
  statsHeading: {
    ...Typography.xl,
    fontWeight: FontWeight.bold,
    color: Colors.white,
    marginBottom: Spacing.sm,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: Spacing.sm,
  },
  statBlock: {
    alignItems: 'center',
  },
  statValue: {
    ...Typography.lg,
    fontWeight: FontWeight.bold,
    color: Colors.white,
  },
  statLabel: {
    ...Typography.sm,
    color: 'rgba(255,255,255,0.8)',
  },
  progressBarTrack: {
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: BorderRadius.full,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.full,
  },
  sectionHeading: {
    ...Typography.lg,
    fontWeight: FontWeight.bold,
    color: Colors.text,
    marginBottom: Spacing.xs,
  },
  badgeGrid: {
    paddingBottom: Spacing.sm,
  },
  badgeRow: {
    justifyContent: 'flex-start',
  },
  emptyContainer: {
    padding: Spacing.lg,
    alignItems: 'center',
  },
  emptyText: {
    ...Typography.md,
    color: Colors.textMuted,
  },
  loadingText: {
    ...Typography.md,
    color: Colors.textMuted,
    marginTop: Spacing.sm,
  },
  errorText: {
    ...Typography.md,
    color: Colors.error,
    textAlign: 'center',
    marginBottom: Spacing.sm,
  },
  retryButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  retryText: {
    ...Typography.md,
    color: Colors.white,
    fontWeight: FontWeight.semiBold,
  },
});
