// Generated by Code Factory
// Spec: SPEC-20260319-003
// Date: 2026-03-19
// DO NOT EDIT

import { Router, type Request, type Response } from 'express';
import type { ApiResponse } from '@phonics-app/shared';

const router = Router();

interface HealthPayload {
  status: 'ok';
  timestamp: string;
}

/**
 * GET /health
 * Lightweight liveness check used by Docker health checks and load balancers.
 * Returns HTTP 200 with `{ status: "ok", timestamp: ISO8601 }`.
 */
router.get('/', (_req: Request, res: Response<ApiResponse<HealthPayload>>) => {
  const payload: ApiResponse<HealthPayload> = {
    status: 'ok',
    data: {
      status: 'ok',
      timestamp: new Date().toISOString(),
    },
    error: null,
    timestamp: new Date().toISOString(),
  };
  res.status(200).json(payload);
});

export default router;
