// Generated by Code Factory
// Spec: SPEC-20260319-005
// Date: 2026-03-19
// DO NOT EDIT

import { Router, type Request, type Response } from 'express';
import { query } from '../db.js';
import type { ApiResponse, PhonicsUnit, Word } from '@phonics-app/shared';

const router = Router();

// ─── DB row types (snake_case from PostgreSQL) ───────────────────────────────

interface PhonicsUnitRow {
  id: number;
  type: string;
  characters: string;
  display_name: string;
  audio_file: string;
  order_index: number;
  created_at: Date;
}

interface WordRow {
  id: number;
  unit_id: number;
  word: string;
  image_file: string | null;
  audio_file: string;
  created_at: Date;
}

// ─── Mappers ─────────────────────────────────────────────────────────────────

function mapUnit(row: PhonicsUnitRow): PhonicsUnit {
  return {
    id: row.id,
    type: row.type as PhonicsUnit['type'],
    characters: row.characters,
    displayName: row.display_name,
    audioFile: row.audio_file,
    orderIndex: row.order_index,
    createdAt: row.created_at,
  };
}

function mapWord(row: WordRow): Word {
  return {
    id: row.id,
    unitId: row.unit_id,
    word: row.word,
    imageFile: row.image_file,
    audioFile: row.audio_file,
    createdAt: row.created_at,
  };
}

// ─── GET /api/lessons ─────────────────────────────────────────────────────────

/**
 * GET /api/lessons
 * Returns all phonics units sorted by orderIndex ascending.
 * Response: ApiResponse<PhonicsUnit[]>
 */
router.get(
  '/',
  async (_req: Request, res: Response<ApiResponse<PhonicsUnit[]>>) => {
    try {
      const rows = await query<PhonicsUnitRow>(
        `SELECT id, type, characters, display_name, audio_file, order_index, created_at
         FROM phonics_units
         ORDER BY order_index ASC`
      );
      const units = rows.map(mapUnit);
      res.status(200).json({
        status: 'ok',
        data: units,
        error: null,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Database error';
      console.error('[lessons] GET / error:', message);
      res.status(500).json({
        status: 'error',
        data: null,
        error: message,
        timestamp: new Date().toISOString(),
      });
    }
  }
);

// ─── GET /api/lessons/:id ─────────────────────────────────────────────────────

interface LessonDetailPayload {
  unit: PhonicsUnit;
  words: Word[];
}

/**
 * GET /api/lessons/:id
 * Returns a single PhonicsUnit with its associated Words.
 * Response: ApiResponse<{ unit: PhonicsUnit, words: Word[] }>
 */
router.get(
  '/:id',
  async (req: Request<{ id: string }>, res: Response<ApiResponse<LessonDetailPayload>>) => {
    const unitId = parseInt(req.params.id, 10);

    if (isNaN(unitId) || unitId <= 0) {
      res.status(404).json({
        status: 'error',
        data: null,
        error: 'Lesson not found',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    try {
      const unitRows = await query<PhonicsUnitRow>(
        `SELECT id, type, characters, display_name, audio_file, order_index, created_at
         FROM phonics_units
         WHERE id = $1`,
        [unitId]
      );

      if (unitRows.length === 0) {
        res.status(404).json({
          status: 'error',
          data: null,
          error: 'Lesson not found',
          timestamp: new Date().toISOString(),
        });
        return;
      }

      const wordRows = await query<WordRow>(
        `SELECT id, unit_id, word, image_file, audio_file, created_at
         FROM words
         WHERE unit_id = $1
         ORDER BY id ASC`,
        [unitId]
      );

      const unit = mapUnit(unitRows[0]!);
      const words = wordRows.map(mapWord);

      res.status(200).json({
        status: 'ok',
        data: { unit, words },
        error: null,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Database error';
      console.error(`[lessons] GET /${unitId} error:`, message);
      res.status(500).json({
        status: 'error',
        data: null,
        error: message,
        timestamp: new Date().toISOString(),
      });
    }
  }
);

export default router;
