// Generated by Code Factory
// Spec: SPEC-20260319-006
// Date: 2026-03-19
// DO NOT EDIT

import { Router, type Request, type Response } from 'express';
import { query } from '../db.js';
import type { ApiResponse, UserProgress, ProgressUpdateBody } from '@phonics-app/shared';

const router = Router();

// ─── DB row types ─────────────────────────────────────────────────────────────

interface UserProgressRow {
  id: number;
  user_id: number;
  unit_id: number;
  completed: boolean;
  score: number;
  last_attempted_at: Date | null;
  created_at: Date;
}

// ─── Mapper ───────────────────────────────────────────────────────────────────

function mapProgress(row: UserProgressRow): UserProgress {
  return {
    id: row.id,
    userId: row.user_id,
    unitId: row.unit_id,
    completed: row.completed,
    score: row.score,
    lastAttemptedAt: row.last_attempted_at,
    createdAt: row.created_at,
  };
}

// ─── GET /api/progress/:userId ────────────────────────────────────────────────

/**
 * GET /api/progress/:userId
 * Returns all user_progress records for the given user.
 * Includes rows for all units the user has attempted; units never attempted
 * are not included (they have no row yet). Frontend fills defaults if needed.
 * Response: ApiResponse<UserProgress[]>
 */
router.get(
  '/:userId',
  async (req: Request<{ userId: string }>, res: Response<ApiResponse<UserProgress[]>>) => {
    const userId = parseInt(req.params.userId, 10);

    if (isNaN(userId) || userId <= 0) {
      res.status(400).json({
        status: 'error',
        data: null,
        error: 'Invalid userId',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    try {
      const rows = await query<UserProgressRow>(
        `SELECT id, user_id, unit_id, completed, score, last_attempted_at, created_at
         FROM user_progress
         WHERE user_id = $1
         ORDER BY unit_id ASC`,
        [userId]
      );

      res.status(200).json({
        status: 'ok',
        data: rows.map(mapProgress),
        error: null,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Database error';
      console.error(`[progress] GET /${userId} error:`, message);
      res.status(500).json({
        status: 'error',
        data: null,
        error: message,
        timestamp: new Date().toISOString(),
      });
    }
  }
);

// ─── POST /api/progress/:userId/unit/:unitId ──────────────────────────────────

/**
 * POST /api/progress/:userId/unit/:unitId
 * Upserts a user_progress record (INSERT … ON CONFLICT DO UPDATE).
 * Body: { completed: boolean, score: 0-100 }
 * lastAttemptedAt is automatically set to NOW().
 * Returns the updated UserProgress record.
 * 404 if unitId does not exist in phonics_units.
 */
router.post(
  '/:userId/unit/:unitId',
  async (
    req: Request<{ userId: string; unitId: string }, ApiResponse<UserProgress>, ProgressUpdateBody>,
    res: Response<ApiResponse<UserProgress>>
  ) => {
    const userId = parseInt(req.params.userId, 10);
    const unitId = parseInt(req.params.unitId, 10);

    if (isNaN(userId) || userId <= 0 || isNaN(unitId) || unitId <= 0) {
      res.status(400).json({
        status: 'error',
        data: null,
        error: 'Invalid userId or unitId',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    const { completed, score } = req.body;

    if (typeof completed !== 'boolean' || typeof score !== 'number') {
      res.status(400).json({
        status: 'error',
        data: null,
        error: 'Body must include completed (boolean) and score (number)',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    if (score < 0 || score > 100) {
      res.status(400).json({
        status: 'error',
        data: null,
        error: 'score must be between 0 and 100',
        timestamp: new Date().toISOString(),
      });
      return;
    }

    try {
      // Verify the unit exists before upserting
      const unitCheck = await query<{ id: number }>(
        `SELECT id FROM phonics_units WHERE id = $1`,
        [unitId]
      );

      if (unitCheck.length === 0) {
        res.status(404).json({
          status: 'error',
          data: null,
          error: 'Unit not found',
          timestamp: new Date().toISOString(),
        });
        return;
      }

      // Upsert: insert or update on (user_id, unit_id) conflict
      const rows = await query<UserProgressRow>(
        `INSERT INTO user_progress (user_id, unit_id, completed, score, last_attempted_at)
         VALUES ($1, $2, $3, $4, NOW())
         ON CONFLICT (user_id, unit_id) DO UPDATE
           SET completed         = EXCLUDED.completed,
               score             = EXCLUDED.score,
               last_attempted_at = NOW()
         RETURNING id, user_id, unit_id, completed, score, last_attempted_at, created_at`,
        [userId, unitId, completed, score]
      );

      const updated = rows[0];
      if (!updated) {
        throw new Error('Upsert returned no rows');
      }

      res.status(200).json({
        status: 'ok',
        data: mapProgress(updated),
        error: null,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Database error';
      console.error(`[progress] POST /${userId}/unit/${unitId} error:`, message);
      res.status(500).json({
        status: 'error',
        data: null,
        error: message,
        timestamp: new Date().toISOString(),
      });
    }
  }
);

export default router;
