// Generated by Code Factory
// Spec: SPEC-20260319-003
// Date: 2026-03-19
// DO NOT EDIT

import corsLib from 'cors';
import type { CorsOptions } from 'cors';

/**
 * CORS middleware factory.
 *
 * Dev  (NODE_ENV !== 'production'): allow all origins ('*')
 * Prod (NODE_ENV === 'production'): restrict to ALLOWED_ORIGINS env var
 *                                    (comma-separated list)
 *
 * Example ALLOWED_ORIGINS: "https://app.phonics.com,https://admin.phonics.com"
 */
function buildCorsOptions(): CorsOptions {
  if (process.env['NODE_ENV'] !== 'production') {
    return { origin: '*' };
  }

  const raw = process.env['ALLOWED_ORIGINS'] ?? '';
  const allowedOrigins = raw
    .split(',')
    .map((o) => o.trim())
    .filter(Boolean);

  if (allowedOrigins.length === 0) {
    console.warn('[CORS] NODE_ENV=production but ALLOWED_ORIGINS is empty — all origins blocked');
  }

  return {
    origin: (
      requestOrigin: string | undefined,
      callback: (err: Error | null, allow?: boolean) => void
    ) => {
      if (requestOrigin === undefined || allowedOrigins.includes(requestOrigin)) {
        callback(null, true);
      } else {
        callback(new Error(`CORS: origin '${requestOrigin}' not allowed`));
      }
    },
    credentials: true,
  };
}

export const corsMiddleware = corsLib(buildCorsOptions());
