// Generated by Code Factory | Spec: SPEC-20260319-010 | Date: 2026-03-19
// DO NOT EDIT

import React, { useCallback, useEffect, useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  ActivityIndicator,
  TouchableOpacity,
  StyleSheet,
  FlatList,
  ListRenderItemInfo,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import type { ApiResponse, Lesson, PhonicsUnit, Word } from '@phonics-app/shared';
import { PhonicsCard } from '../../components/PhonicsCard';
import { WordExample } from '../../components/WordExample';
import { useAudio } from '../../hooks/useAudio';
import { Colors, Typography, Spacing, FontWeight, BorderRadius } from '../../constants/theme';

// ─── Config ───────────────────────────────────────────────────────────────────

const API_BASE_URL = process.env['EXPO_PUBLIC_API_URL'] ?? 'http://localhost:3000';

// ─── Types ────────────────────────────────────────────────────────────────────

interface LessonDetail {
  lesson: Lesson;
  unit: PhonicsUnit;
  words: Word[];
}

// ─── Data fetching ────────────────────────────────────────────────────────────

async function fetchLessonDetail(id: number): Promise<LessonDetail> {
  const lessonRes = await fetch(`${API_BASE_URL}/api/lessons/${id}`);
  if (!lessonRes.ok) {
    throw new Error(`HTTP ${lessonRes.status}: failed to fetch lesson`);
  }
  const lessonJson = (await lessonRes.json()) as ApiResponse<LessonDetail>;
  if (lessonJson.status !== 'ok' || lessonJson.data === null) {
    throw new Error(lessonJson.error ?? 'Unknown error fetching lesson');
  }
  return lessonJson.data;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function LessonDetailScreen(): JSX.Element {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const lessonId = parseInt(id ?? '0', 10);

  const [detail, setDetail] = useState<LessonDetail | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  // Active audio file being played (track which button is "active")
  const [activeAudioFile, setActiveAudioFile] = useState<string | null>(null);

  const { play, isPlaying, isLoading: audioLoading } = useAudio();

  // Fetch lesson on mount
  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    setError(null);

    void (async () => {
      try {
        const data = await fetchLessonDetail(lessonId);
        if (!cancelled) {
          setDetail(data);
        }
      } catch (err: unknown) {
        if (!cancelled) {
          const message = err instanceof Error ? err.message : String(err);
          setError(message);
        }
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [lessonId]);

  const handlePlayAudio = useCallback(
    (audioFile: string) => {
      setActiveAudioFile(audioFile);
      void play(audioFile);
    },
    [play],
  );

  const renderWord = useCallback(
    ({ item }: ListRenderItemInfo<Word>) => (
      <WordExample
        word={item}
        isPlaying={isPlaying && activeAudioFile === item.audioFile}
        isLoading={audioLoading && activeAudioFile === item.audioFile}
        onPlayAudio={handlePlayAudio}
      />
    ),
    [isPlaying, audioLoading, activeAudioFile, handlePlayAudio],
  );

  const keyExtractor = useCallback((item: Word) => String(item.id), []);

  if (error !== null) {
    return (
      <View style={styles.centered}>
        <Text style={styles.errorText}>{error}</Text>
        <TouchableOpacity
          onPress={() => router.back()}
          style={styles.backButton}
          testID="back-button"
        >
          <Text style={styles.backButtonText}>← Go Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (isLoading || detail === null) {
    return (
      <View style={styles.centered}>
        <ActivityIndicator size="large" color={Colors.primary} testID="loading-indicator" />
        <Text style={styles.loadingText}>Loading lesson…</Text>
      </View>
    );
  }

  const { lesson, unit, words } = detail;

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
      testID="lesson-scroll"
    >
      {/* Lesson header */}
      <View style={styles.header} testID="lesson-header">
        <Text style={styles.lessonTitle}>{lesson.title}</Text>
        <View style={styles.difficultyRow}>
          <Text style={styles.difficultyLabel}>
            {'★'.repeat(lesson.difficulty)}{'☆'.repeat(5 - lesson.difficulty)}
          </Text>
          <Text style={styles.exerciseType}>{lesson.exerciseType.replace(/_/g, ' ')}</Text>
        </View>
      </View>

      {/* Phonics unit card */}
      <PhonicsCard
        unit={unit}
        isPlaying={isPlaying && activeAudioFile === unit.audioFile}
        isLoading={audioLoading && activeAudioFile === unit.audioFile}
        onPlayAudio={handlePlayAudio}
      />

      {/* Word examples section */}
      <Text style={styles.sectionHeading}>Word Examples</Text>
      {words.length === 0 ? (
        <Text style={styles.noWordsText} testID="no-words">
          No word examples for this lesson.
        </Text>
      ) : (
        <FlatList<Word>
          data={words}
          renderItem={renderWord}
          keyExtractor={keyExtractor}
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.wordList}
          testID="words-list"
          scrollEnabled
        />
      )}
    </ScrollView>
  );
}

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    paddingBottom: Spacing.xxl,
    paddingTop: Spacing.sm,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  header: {
    paddingHorizontal: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  lessonTitle: {
    ...Typography.xl,
    fontWeight: FontWeight.bold,
    color: Colors.text,
    marginBottom: Spacing.xxs,
  },
  difficultyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  difficultyLabel: {
    ...Typography.md,
    color: Colors.secondary,
  },
  exerciseType: {
    ...Typography.sm,
    color: Colors.textMuted,
    textTransform: 'capitalize',
  },
  sectionHeading: {
    ...Typography.lg,
    fontWeight: FontWeight.bold,
    color: Colors.text,
    paddingHorizontal: Spacing.sm,
    marginTop: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  wordList: {
    paddingHorizontal: Spacing.sm,
  },
  noWordsText: {
    ...Typography.md,
    color: Colors.textMuted,
    paddingHorizontal: Spacing.sm,
  },
  loadingText: {
    ...Typography.md,
    color: Colors.textMuted,
    marginTop: Spacing.sm,
  },
  errorText: {
    ...Typography.md,
    color: Colors.error,
    textAlign: 'center',
    marginBottom: Spacing.sm,
  },
  backButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.md,
  },
  backButtonText: {
    ...Typography.md,
    color: Colors.white,
    fontWeight: FontWeight.semiBold,
  },
});
