// Generated by Code Factory
// Spec: SPEC-20260319-003
// Date: 2026-03-19
// DO NOT EDIT

/**
 * Integration tests for the API server scaffold.
 * Tests: server startup (app initialises), health endpoint, 404 handler.
 * Database pool is mocked to avoid requiring a live PostgreSQL instance in CI.
 */

import request from 'supertest';

// ─── Mock DB before importing app ─────────────────────────────────────────────
jest.mock('../src/db.js', () => ({
  __esModule: true,
  default: { query: jest.fn(), end: jest.fn() },
  query: jest.fn(),
  getClient: jest.fn(),
  closePool: jest.fn().mockResolvedValue(undefined),
}));

// eslint-disable-next-line import/first
import { app } from '../src/index.js';

describe('API Server — health check', () => {
  it('GET /health returns 200 with status ok', async () => {
    const res = await request(app).get('/health');
    expect(res.status).toBe(200);
    expect(res.body.status).toBe('ok');
  });

  it('GET /health returns a data object with timestamp', async () => {
    const res = await request(app).get('/health');
    expect(res.body.data).toBeDefined();
    expect(typeof res.body.data.timestamp).toBe('string');
    // Verify it is a valid ISO 8601 string
    const ts = new Date(res.body.data.timestamp as string);
    expect(ts.getTime()).not.toBeNaN();
  });

  it('GET /health includes top-level timestamp in envelope', async () => {
    const res = await request(app).get('/health');
    expect(res.body.timestamp).toBeDefined();
    expect(res.body.error).toBeNull();
    expect(res.body.status).toBe('ok');
  });
});

describe('API Server — 404 handler', () => {
  it('returns 404 for an unknown route', async () => {
    const res = await request(app).get('/no-such-endpoint');
    expect(res.status).toBe(404);
    expect(res.body.status).toBe('error');
  });

  it('404 response includes error field', async () => {
    const res = await request(app).get('/nonexistent');
    expect(res.body.error).toBeTruthy();
    expect(res.body.data).toBeNull();
  });
});

describe('API Server — JSON middleware', () => {
  it('sets Content-Type application/json for /health', async () => {
    const res = await request(app).get('/health');
    expect(res.headers['content-type']).toMatch(/application\/json/);
  });
});
