// Generated by Code Factory | Spec: SPEC-20260319-008 | Date: 2026-03-19
// DO NOT EDIT

import React from 'react';
import {
  TouchableOpacity,
  View,
  Text,
  StyleSheet,
  AccessibilityRole,
} from 'react-native';
import type { Lesson } from '@phonics-app/shared';
import { Colors, Typography, Spacing, BorderRadius, FontWeight, Shadow } from '../constants/theme';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface LessonCardProps {
  lesson: Lesson;
  onPress: (lessonId: number) => void;
  testID?: string;
}

// ─── Difficulty label mapping ─────────────────────────────────────────────────

const DIFFICULTY_LABELS: Record<number, string> = {
  1: 'Beginner',
  2: 'Easy',
  3: 'Medium',
  4: 'Hard',
  5: 'Advanced',
};

const DIFFICULTY_COLORS: Record<number, string> = {
  1: '#22C55E',
  2: '#84CC16',
  3: '#F59E0B',
  4: '#EF4444',
  5: '#7C3AED',
};

const EXERCISE_TYPE_LABELS: Record<string, string> = {
  tap_to_hear: 'Tap to Hear',
  match_sound: 'Match Sound',
  fill_blank: 'Fill in the Blank',
};

// ─── Component ────────────────────────────────────────────────────────────────

export const LessonCard = React.memo(function LessonCard({
  lesson,
  onPress,
  testID,
}: LessonCardProps): JSX.Element {
  const difficultyLabel = DIFFICULTY_LABELS[lesson.difficulty] ?? `Level ${lesson.difficulty}`;
  const difficultyColor = DIFFICULTY_COLORS[lesson.difficulty] ?? Colors.textMuted;
  const exerciseLabel =
    EXERCISE_TYPE_LABELS[lesson.exerciseType] ?? lesson.exerciseType;

  const handlePress = React.useCallback(() => {
    onPress(lesson.id);
  }, [lesson.id, onPress]);

  return (
    <TouchableOpacity
      style={styles.card}
      onPress={handlePress}
      activeOpacity={0.8}
      accessibilityRole={'button' as AccessibilityRole}
      accessibilityLabel={`Lesson: ${lesson.title}, ${difficultyLabel}`}
      testID={testID ?? `lesson-card-${lesson.id}`}
    >
      <View style={styles.content}>
        <Text style={styles.title} numberOfLines={2}>
          {lesson.title}
        </Text>
        <Text style={styles.exerciseType}>{exerciseLabel}</Text>
      </View>
      <View style={styles.badge}>
        <View style={[styles.difficultyDot, { backgroundColor: difficultyColor }]} />
        <Text style={[styles.difficultyText, { color: difficultyColor }]}>
          {difficultyLabel}
        </Text>
      </View>
    </TouchableOpacity>
  );
});

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    padding: Spacing.sm,
    marginHorizontal: Spacing.sm,
    marginVertical: Spacing.xs / 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    ...Shadow.md,
  },
  content: {
    flex: 1,
    marginRight: Spacing.sm,
  },
  title: {
    ...Typography.md,
    fontWeight: FontWeight.semiBold,
    color: Colors.text,
    marginBottom: Spacing.xxs,
  },
  exerciseType: {
    ...Typography.sm,
    color: Colors.textMuted,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  difficultyDot: {
    width: 8,
    height: 8,
    borderRadius: BorderRadius.full,
  },
  difficultyText: {
    ...Typography.sm,
    fontWeight: FontWeight.medium,
  },
});
