// Generated by Code Factory | Spec: SPEC-20260319-010 | Date: 2026-03-19
// DO NOT EDIT

import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import type { PhonicsUnit } from '@phonics-app/shared';
import { Colors, Typography, Spacing, BorderRadius, FontWeight, Shadow } from '../constants/theme';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface PhonicsCardProps {
  unit: PhonicsUnit;
  isPlaying: boolean;
  isLoading: boolean;
  onPlayAudio: (audioFile: string) => void;
  testID?: string;
}

// ─── Unit type display label ──────────────────────────────────────────────────

const UNIT_TYPE_LABELS: Record<string, string> = {
  letter: 'Letter',
  digraph: 'Digraph',
  vowelTeam: 'Vowel Team',
};

// ─── Component ────────────────────────────────────────────────────────────────

export const PhonicsCard = React.memo(function PhonicsCard({
  unit,
  isPlaying,
  isLoading,
  onPlayAudio,
  testID,
}: PhonicsCardProps): JSX.Element {
  const typeLabel = UNIT_TYPE_LABELS[unit.type] ?? unit.type;

  const handlePlayPress = React.useCallback(() => {
    onPlayAudio(unit.audioFile);
  }, [unit.audioFile, onPlayAudio]);

  return (
    <View
      style={styles.card}
      testID={testID ?? `phonics-card-${unit.id}`}
      accessible
      accessibilityLabel={`${typeLabel}: ${unit.displayName}`}
    >
      {/* Type badge */}
      <View style={styles.typeBadge}>
        <Text style={styles.typeLabel}>{typeLabel}</Text>
      </View>

      {/* Main phoneme display */}
      <Text style={styles.characters} accessibilityRole="text">
        {unit.characters}
      </Text>
      <Text style={styles.displayName}>{unit.displayName}</Text>

      {/* Play audio button */}
      <TouchableOpacity
        style={[styles.playButton, isPlaying && styles.playButtonActive]}
        onPress={handlePlayPress}
        disabled={isLoading}
        accessibilityLabel={isPlaying ? 'Stop audio' : 'Play phoneme sound'}
        accessibilityRole="button"
        testID={`play-button-${unit.id}`}
      >
        {isLoading ? (
          <ActivityIndicator size="small" color={Colors.white} testID={`audio-loading-${unit.id}`} />
        ) : (
          <Text style={styles.playButtonText}>{isPlaying ? '⏸' : '▶'}</Text>
        )}
        <Text style={styles.playButtonLabel}>
          {isLoading ? 'Loading…' : isPlaying ? 'Playing' : 'Hear it'}
        </Text>
      </TouchableOpacity>
    </View>
  );
});

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    marginHorizontal: Spacing.sm,
    marginBottom: Spacing.sm,
    alignItems: 'center',
    ...Shadow.md,
  },
  typeBadge: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xxs,
    marginBottom: Spacing.sm,
  },
  typeLabel: {
    ...Typography.sm,
    fontWeight: FontWeight.semiBold,
    color: Colors.white,
    textTransform: 'uppercase',
  },
  characters: {
    fontSize: 64,
    lineHeight: 80,
    fontWeight: FontWeight.bold,
    color: Colors.primary,
    marginBottom: Spacing.xs,
  },
  displayName: {
    ...Typography.lg,
    fontWeight: FontWeight.medium,
    color: Colors.textMuted,
    marginBottom: Spacing.md,
  },
  playButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.secondary,
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    gap: Spacing.xs,
  },
  playButtonActive: {
    backgroundColor: Colors.primary,
  },
  playButtonText: {
    fontSize: 20,
  },
  playButtonLabel: {
    ...Typography.md,
    fontWeight: FontWeight.semiBold,
    color: Colors.white,
  },
});
