// Generated by Code Factory | Spec: SPEC-20260319-011 | Date: 2026-03-19
// DO NOT EDIT

import React from 'react';
import { TouchableOpacity, View, Text, StyleSheet } from 'react-native';
import type { UserProgress } from '@phonics-app/shared';
import { Colors, Typography, Spacing, BorderRadius, FontWeight, Shadow } from '../constants/theme';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ProgressBadgeProps {
  progress: UserProgress;
  unitName: string;
  onPress: (lessonId: number) => void;
  testID?: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getScoreColor(score: number): string {
  if (score >= 80) return Colors.success;
  if (score >= 50) return Colors.warning;
  return Colors.error;
}

function getScoreLabel(score: number, completed: boolean): string {
  if (!completed) return 'Not started';
  if (score >= 80) return '⭐ Excellent';
  if (score >= 50) return '✓ Passing';
  return '✗ Needs work';
}

// ─── Component ────────────────────────────────────────────────────────────────

export const ProgressBadge = React.memo(function ProgressBadge({
  progress,
  unitName,
  onPress,
  testID,
}: ProgressBadgeProps): JSX.Element {
  const scoreColor = progress.completed ? getScoreColor(progress.score) : Colors.border;
  const scoreLabel = getScoreLabel(progress.score, progress.completed);

  const handlePress = React.useCallback(() => {
    // Navigate to the lesson associated with this unit
    onPress(progress.unitId);
  }, [progress.unitId, onPress]);

  return (
    <TouchableOpacity
      style={[styles.badge, progress.completed && styles.badgeCompleted]}
      onPress={handlePress}
      activeOpacity={0.8}
      accessibilityLabel={`${unitName}: ${scoreLabel}, score ${progress.score}`}
      accessibilityRole="button"
      testID={testID ?? `progress-badge-${progress.unitId}`}
    >
      <View style={[styles.scoreBubble, { backgroundColor: scoreColor }]}>
        <Text style={styles.scoreText}>{progress.completed ? String(progress.score) : '–'}</Text>
      </View>
      <Text style={styles.unitName} numberOfLines={2}>
        {unitName}
      </Text>
      <Text style={[styles.statusLabel, { color: scoreColor }]}>{scoreLabel}</Text>
    </TouchableOpacity>
  );
});

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  badge: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    padding: Spacing.sm,
    width: 140,
    alignItems: 'center',
    margin: Spacing.xs / 2,
    borderWidth: 1.5,
    borderColor: Colors.border,
    ...Shadow.sm,
  },
  badgeCompleted: {
    borderColor: Colors.primary,
  },
  scoreBubble: {
    width: 56,
    height: 56,
    borderRadius: BorderRadius.full,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.xs,
  },
  scoreText: {
    ...Typography.lg,
    fontWeight: FontWeight.bold,
    color: Colors.white,
  },
  unitName: {
    ...Typography.sm,
    fontWeight: FontWeight.semiBold,
    color: Colors.text,
    textAlign: 'center',
    marginBottom: Spacing.xxs,
  },
  statusLabel: {
    ...Typography.sm,
    fontWeight: FontWeight.medium,
    textAlign: 'center',
  },
});
