// Generated by Code Factory | Spec: SPEC-20260319-010 | Date: 2026-03-19
// DO NOT EDIT

import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  Image,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import type { Word } from '@phonics-app/shared';
import { Colors, Typography, Spacing, BorderRadius, FontWeight, Shadow } from '../constants/theme';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface WordExampleProps {
  word: Word;
  isPlaying: boolean;
  isLoading: boolean;
  onPlayAudio: (audioFile: string) => void;
  testID?: string;
}

// ─── Component ────────────────────────────────────────────────────────────────

export const WordExample = React.memo(function WordExample({
  word,
  isPlaying,
  isLoading,
  onPlayAudio,
  testID,
}: WordExampleProps): JSX.Element {
  const handlePlayPress = React.useCallback(() => {
    onPlayAudio(word.audioFile);
  }, [word.audioFile, onPlayAudio]);

  return (
    <View
      style={styles.container}
      testID={testID ?? `word-example-${word.id}`}
      accessible
      accessibilityLabel={`Word: ${word.word}`}
    >
      {/* Image (optional) */}
      {word.imageFile !== null && (
        <Image
          source={{ uri: word.imageFile }}
          style={styles.image}
          resizeMode="cover"
          accessibilityLabel={`Image for ${word.word}`}
          testID={`word-image-${word.id}`}
        />
      )}

      {/* Word text */}
      <Text style={styles.wordText} accessibilityRole="text">
        {word.word}
      </Text>

      {/* Play audio button */}
      <TouchableOpacity
        style={[styles.audioButton, isPlaying && styles.audioButtonActive]}
        onPress={handlePlayPress}
        disabled={isLoading}
        accessibilityLabel={isPlaying ? 'Stop word audio' : `Hear the word ${word.word}`}
        accessibilityRole="button"
        testID={`word-play-button-${word.id}`}
      >
        {isLoading ? (
          <ActivityIndicator size="small" color={Colors.primary} testID={`word-loading-${word.id}`} />
        ) : (
          <Text style={styles.audioIcon}>{isPlaying ? '⏸' : '🔊'}</Text>
        )}
      </TouchableOpacity>
    </View>
  );
});

// ─── Styles ───────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    padding: Spacing.sm,
    alignItems: 'center',
    width: 120,
    margin: Spacing.xs / 2,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Shadow.sm,
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: BorderRadius.md,
    marginBottom: Spacing.xs,
    backgroundColor: Colors.background,
  },
  wordText: {
    ...Typography.md,
    fontWeight: FontWeight.bold,
    color: Colors.text,
    marginBottom: Spacing.xs,
    textAlign: 'center',
  },
  audioButton: {
    width: 36,
    height: 36,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: Colors.primary,
  },
  audioButtonActive: {
    backgroundColor: Colors.primary,
  },
  audioIcon: {
    fontSize: 18,
  },
});
