-- Generated by Code Factory
-- Spec: SPEC-20260319-002
-- Date: 2026-03-19
-- DO NOT EDIT — regenerate from spec instead
--
-- Idempotent schema for the Phonics App
-- PostgreSQL 16+
-- Run: psql -U $DB_USER -d $DB_NAME -f schema.sql

-- ─── Users ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    avatar      VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_created_at ON users (created_at);

-- ─── Phonics Units ─────────────────────────────────────────────────────────────
-- type: 'letter' | 'digraph' | 'vowel_team'
CREATE TABLE IF NOT EXISTS phonics_units (
    id           SERIAL PRIMARY KEY,
    type         VARCHAR(20)  NOT NULL CHECK (type IN ('letter', 'digraph', 'vowel_team')),
    characters   VARCHAR(10)  NOT NULL UNIQUE,    -- e.g. 'a', 'sh', 'ai'
    display_name VARCHAR(50)  NOT NULL,           -- e.g. 'Letter A', 'Digraph SH'
    audio_file   VARCHAR(255) NOT NULL,           -- e.g. 'phoneme-a.mp3'
    order_index  INTEGER      NOT NULL,           -- determines lesson order
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_phonics_units_type        ON phonics_units (type);
CREATE INDEX IF NOT EXISTS idx_phonics_units_order_index ON phonics_units (order_index);

-- ─── Lessons ──────────────────────────────────────────────────────────────────
-- exercise_type: 'tap_to_hear' | 'match_sound' | 'fill_blank'
CREATE TABLE IF NOT EXISTS lessons (
    id             SERIAL PRIMARY KEY,
    unit_id        INTEGER      NOT NULL REFERENCES phonics_units (id) ON DELETE CASCADE,
    title          VARCHAR(100) NOT NULL,
    difficulty     SMALLINT     NOT NULL DEFAULT 1 CHECK (difficulty BETWEEN 1 AND 5),
    exercise_type  VARCHAR(20)  NOT NULL CHECK (exercise_type IN ('tap_to_hear', 'match_sound', 'fill_blank')),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lessons_unit_id    ON lessons (unit_id);
CREATE INDEX IF NOT EXISTS idx_lessons_difficulty ON lessons (difficulty);

-- ─── Words ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS words (
    id          SERIAL PRIMARY KEY,
    unit_id     INTEGER      NOT NULL REFERENCES phonics_units (id) ON DELETE CASCADE,
    word        VARCHAR(50)  NOT NULL,
    image_file  VARCHAR(255),                    -- optional illustration
    audio_file  VARCHAR(255) NOT NULL,           -- e.g. 'word-apple.mp3'
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_words_unit_id ON words (unit_id);
CREATE INDEX IF NOT EXISTS idx_words_word    ON words (word);

-- ─── User Progress ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_progress (
    id                  SERIAL PRIMARY KEY,
    user_id             INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    unit_id             INTEGER     NOT NULL REFERENCES phonics_units (id) ON DELETE CASCADE,
    completed           BOOLEAN     NOT NULL DEFAULT FALSE,
    score               SMALLINT    NOT NULL DEFAULT 0 CHECK (score BETWEEN 0 AND 100),
    last_attempted_at   TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, unit_id)
);

CREATE INDEX IF NOT EXISTS idx_user_progress_user_id ON user_progress (user_id);
CREATE INDEX IF NOT EXISTS idx_user_progress_unit_id ON user_progress (unit_id);
CREATE INDEX IF NOT EXISTS idx_user_progress_completed ON user_progress (completed);
