-- Generated by Code Factory
-- Spec: SPEC-20260319-002
-- Date: 2026-03-19
-- DO NOT EDIT — regenerate from spec instead
--
-- Seed data: 26 letter sounds + 10 digraphs/vowel teams
-- Idempotent: uses INSERT ... ON CONFLICT DO NOTHING
-- PostgreSQL 16+

-- ─── Phonics Units: 26 Letters ────────────────────────────────────────────────
INSERT INTO phonics_units (type, characters, display_name, audio_file, order_index) VALUES
    ('letter', 'a', 'Letter A', 'phoneme-a.mp3',  1),
    ('letter', 'b', 'Letter B', 'phoneme-b.mp3',  2),
    ('letter', 'c', 'Letter C', 'phoneme-c.mp3',  3),
    ('letter', 'd', 'Letter D', 'phoneme-d.mp3',  4),
    ('letter', 'e', 'Letter E', 'phoneme-e.mp3',  5),
    ('letter', 'f', 'Letter F', 'phoneme-f.mp3',  6),
    ('letter', 'g', 'Letter G', 'phoneme-g.mp3',  7),
    ('letter', 'h', 'Letter H', 'phoneme-h.mp3',  8),
    ('letter', 'i', 'Letter I', 'phoneme-i.mp3',  9),
    ('letter', 'j', 'Letter J', 'phoneme-j.mp3', 10),
    ('letter', 'k', 'Letter K', 'phoneme-k.mp3', 11),
    ('letter', 'l', 'Letter L', 'phoneme-l.mp3', 12),
    ('letter', 'm', 'Letter M', 'phoneme-m.mp3', 13),
    ('letter', 'n', 'Letter N', 'phoneme-n.mp3', 14),
    ('letter', 'o', 'Letter O', 'phoneme-o.mp3', 15),
    ('letter', 'p', 'Letter P', 'phoneme-p.mp3', 16),
    ('letter', 'q', 'Letter Q', 'phoneme-q.mp3', 17),
    ('letter', 'r', 'Letter R', 'phoneme-r.mp3', 18),
    ('letter', 's', 'Letter S', 'phoneme-s.mp3', 19),
    ('letter', 't', 'Letter T', 'phoneme-t.mp3', 20),
    ('letter', 'u', 'Letter U', 'phoneme-u.mp3', 21),
    ('letter', 'v', 'Letter V', 'phoneme-v.mp3', 22),
    ('letter', 'w', 'Letter W', 'phoneme-w.mp3', 23),
    ('letter', 'x', 'Letter X', 'phoneme-x.mp3', 24),
    ('letter', 'y', 'Letter Y', 'phoneme-y.mp3', 25),
    ('letter', 'z', 'Letter Z', 'phoneme-z.mp3', 26)
ON CONFLICT (characters) DO NOTHING;

-- ─── Phonics Units: 5 Digraphs ────────────────────────────────────────────────
INSERT INTO phonics_units (type, characters, display_name, audio_file, order_index) VALUES
    ('digraph', 'sh', 'Digraph SH', 'phoneme-sh.mp3', 27),
    ('digraph', 'ch', 'Digraph CH', 'phoneme-ch.mp3', 28),
    ('digraph', 'th', 'Digraph TH', 'phoneme-th.mp3', 29),
    ('digraph', 'ph', 'Digraph PH', 'phoneme-ph.mp3', 30),
    ('digraph', 'wh', 'Digraph WH', 'phoneme-wh.mp3', 31)
ON CONFLICT (characters) DO NOTHING;

-- ─── Phonics Units: 5 Vowel Teams ─────────────────────────────────────────────
INSERT INTO phonics_units (type, characters, display_name, audio_file, order_index) VALUES
    ('vowel_team', 'ai', 'Vowel Team AI', 'phoneme-ai.mp3', 32),
    ('vowel_team', 'oa', 'Vowel Team OA', 'phoneme-oa.mp3', 33),
    ('vowel_team', 'ee', 'Vowel Team EE', 'phoneme-ee.mp3', 34),
    ('vowel_team', 'ou', 'Vowel Team OU', 'phoneme-ou.mp3', 35),
    ('vowel_team', 'oy', 'Vowel Team OY', 'phoneme-oy.mp3', 36)
ON CONFLICT (characters) DO NOTHING;

-- ─── Example Words (at least 1 per phonics unit) ──────────────────────────────
-- Words are linked to units via a subquery to avoid hardcoded IDs.

INSERT INTO words (unit_id, word, image_file, audio_file)
SELECT id, 'apple',    'img-apple.png',    'word-apple.mp3'    FROM phonics_units WHERE characters = 'a'
UNION ALL
SELECT id, 'ant',      'img-ant.png',      'word-ant.mp3'      FROM phonics_units WHERE characters = 'a'
UNION ALL
SELECT id, 'ball',     'img-ball.png',     'word-ball.mp3'     FROM phonics_units WHERE characters = 'b'
UNION ALL
SELECT id, 'bat',      'img-bat.png',      'word-bat.mp3'      FROM phonics_units WHERE characters = 'b'
UNION ALL
SELECT id, 'cat',      'img-cat.png',      'word-cat.mp3'      FROM phonics_units WHERE characters = 'c'
UNION ALL
SELECT id, 'cup',      'img-cup.png',      'word-cup.mp3'      FROM phonics_units WHERE characters = 'c'
UNION ALL
SELECT id, 'dog',      'img-dog.png',      'word-dog.mp3'      FROM phonics_units WHERE characters = 'd'
UNION ALL
SELECT id, 'duck',     'img-duck.png',     'word-duck.mp3'     FROM phonics_units WHERE characters = 'd'
UNION ALL
SELECT id, 'egg',      'img-egg.png',      'word-egg.mp3'      FROM phonics_units WHERE characters = 'e'
UNION ALL
SELECT id, 'elephant', 'img-elephant.png', 'word-elephant.mp3' FROM phonics_units WHERE characters = 'e'
UNION ALL
SELECT id, 'fish',     'img-fish.png',     'word-fish.mp3'     FROM phonics_units WHERE characters = 'f'
UNION ALL
SELECT id, 'frog',     'img-frog.png',     'word-frog.mp3'     FROM phonics_units WHERE characters = 'f'
UNION ALL
SELECT id, 'goat',     'img-goat.png',     'word-goat.mp3'     FROM phonics_units WHERE characters = 'g'
UNION ALL
SELECT id, 'gift',     'img-gift.png',     'word-gift.mp3'     FROM phonics_units WHERE characters = 'g'
UNION ALL
SELECT id, 'hat',      'img-hat.png',      'word-hat.mp3'      FROM phonics_units WHERE characters = 'h'
UNION ALL
SELECT id, 'hen',      'img-hen.png',      'word-hen.mp3'      FROM phonics_units WHERE characters = 'h'
UNION ALL
SELECT id, 'igloo',    'img-igloo.png',    'word-igloo.mp3'    FROM phonics_units WHERE characters = 'i'
UNION ALL
SELECT id, 'ink',      'img-ink.png',      'word-ink.mp3'      FROM phonics_units WHERE characters = 'i'
UNION ALL
SELECT id, 'jar',      'img-jar.png',      'word-jar.mp3'      FROM phonics_units WHERE characters = 'j'
UNION ALL
SELECT id, 'jellyfish','img-jellyfish.png','word-jellyfish.mp3'FROM phonics_units WHERE characters = 'j'
UNION ALL
SELECT id, 'kite',     'img-kite.png',     'word-kite.mp3'     FROM phonics_units WHERE characters = 'k'
UNION ALL
SELECT id, 'king',     'img-king.png',     'word-king.mp3'     FROM phonics_units WHERE characters = 'k'
UNION ALL
SELECT id, 'lion',     'img-lion.png',     'word-lion.mp3'     FROM phonics_units WHERE characters = 'l'
UNION ALL
SELECT id, 'lamp',     'img-lamp.png',     'word-lamp.mp3'     FROM phonics_units WHERE characters = 'l'
UNION ALL
SELECT id, 'moon',     'img-moon.png',     'word-moon.mp3'     FROM phonics_units WHERE characters = 'm'
UNION ALL
SELECT id, 'map',      'img-map.png',      'word-map.mp3'      FROM phonics_units WHERE characters = 'm'
UNION ALL
SELECT id, 'nest',     'img-nest.png',     'word-nest.mp3'     FROM phonics_units WHERE characters = 'n'
UNION ALL
SELECT id, 'nut',      'img-nut.png',      'word-nut.mp3'      FROM phonics_units WHERE characters = 'n'
UNION ALL
SELECT id, 'octopus',  'img-octopus.png',  'word-octopus.mp3'  FROM phonics_units WHERE characters = 'o'
UNION ALL
SELECT id, 'owl',      'img-owl.png',      'word-owl.mp3'      FROM phonics_units WHERE characters = 'o'
UNION ALL
SELECT id, 'pig',      'img-pig.png',      'word-pig.mp3'      FROM phonics_units WHERE characters = 'p'
UNION ALL
SELECT id, 'pen',      'img-pen.png',      'word-pen.mp3'      FROM phonics_units WHERE characters = 'p'
UNION ALL
SELECT id, 'queen',    'img-queen.png',    'word-queen.mp3'    FROM phonics_units WHERE characters = 'q'
UNION ALL
SELECT id, 'quilt',    'img-quilt.png',    'word-quilt.mp3'    FROM phonics_units WHERE characters = 'q'
UNION ALL
SELECT id, 'rabbit',   'img-rabbit.png',   'word-rabbit.mp3'   FROM phonics_units WHERE characters = 'r'
UNION ALL
SELECT id, 'rose',     'img-rose.png',     'word-rose.mp3'     FROM phonics_units WHERE characters = 'r'
UNION ALL
SELECT id, 'sun',      'img-sun.png',      'word-sun.mp3'      FROM phonics_units WHERE characters = 's'
UNION ALL
SELECT id, 'sock',     'img-sock.png',     'word-sock.mp3'     FROM phonics_units WHERE characters = 's'
UNION ALL
SELECT id, 'tiger',    'img-tiger.png',    'word-tiger.mp3'    FROM phonics_units WHERE characters = 't'
UNION ALL
SELECT id, 'top',      'img-top.png',      'word-top.mp3'      FROM phonics_units WHERE characters = 't'
UNION ALL
SELECT id, 'umbrella', 'img-umbrella.png', 'word-umbrella.mp3' FROM phonics_units WHERE characters = 'u'
UNION ALL
SELECT id, 'up',       'img-up.png',       'word-up.mp3'       FROM phonics_units WHERE characters = 'u'
UNION ALL
SELECT id, 'van',      'img-van.png',      'word-van.mp3'      FROM phonics_units WHERE characters = 'v'
UNION ALL
SELECT id, 'vest',     'img-vest.png',     'word-vest.mp3'     FROM phonics_units WHERE characters = 'v'
UNION ALL
SELECT id, 'wolf',     'img-wolf.png',     'word-wolf.mp3'     FROM phonics_units WHERE characters = 'w'
UNION ALL
SELECT id, 'web',      'img-web.png',      'word-web.mp3'      FROM phonics_units WHERE characters = 'w'
UNION ALL
SELECT id, 'fox',      'img-fox.png',      'word-fox.mp3'      FROM phonics_units WHERE characters = 'x'
UNION ALL
SELECT id, 'box',      'img-box.png',      'word-box.mp3'      FROM phonics_units WHERE characters = 'x'
UNION ALL
SELECT id, 'yak',      'img-yak.png',      'word-yak.mp3'      FROM phonics_units WHERE characters = 'y'
UNION ALL
SELECT id, 'yarn',     'img-yarn.png',     'word-yarn.mp3'     FROM phonics_units WHERE characters = 'y'
UNION ALL
SELECT id, 'zebra',    'img-zebra.png',    'word-zebra.mp3'    FROM phonics_units WHERE characters = 'z'
UNION ALL
SELECT id, 'zip',      'img-zip.png',      'word-zip.mp3'      FROM phonics_units WHERE characters = 'z'
-- Digraphs
UNION ALL
SELECT id, 'ship',     'img-ship.png',     'word-ship.mp3'     FROM phonics_units WHERE characters = 'sh'
UNION ALL
SELECT id, 'shell',    'img-shell.png',    'word-shell.mp3'    FROM phonics_units WHERE characters = 'sh'
UNION ALL
SELECT id, 'chin',     'img-chin.png',     'word-chin.mp3'     FROM phonics_units WHERE characters = 'ch'
UNION ALL
SELECT id, 'chair',    'img-chair.png',    'word-chair.mp3'    FROM phonics_units WHERE characters = 'ch'
UNION ALL
SELECT id, 'think',    'img-think.png',    'word-think.mp3'    FROM phonics_units WHERE characters = 'th'
UNION ALL
SELECT id, 'thumb',    'img-thumb.png',    'word-thumb.mp3'    FROM phonics_units WHERE characters = 'th'
UNION ALL
SELECT id, 'phone',    'img-phone.png',    'word-phone.mp3'    FROM phonics_units WHERE characters = 'ph'
UNION ALL
SELECT id, 'photo',    'img-photo.png',    'word-photo.mp3'    FROM phonics_units WHERE characters = 'ph'
UNION ALL
SELECT id, 'wheel',    'img-wheel.png',    'word-wheel.mp3'    FROM phonics_units WHERE characters = 'wh'
UNION ALL
SELECT id, 'whale',    'img-whale.png',    'word-whale.mp3'    FROM phonics_units WHERE characters = 'wh'
-- Vowel teams
UNION ALL
SELECT id, 'rain',     'img-rain.png',     'word-rain.mp3'     FROM phonics_units WHERE characters = 'ai'
UNION ALL
SELECT id, 'tail',     'img-tail.png',     'word-tail.mp3'     FROM phonics_units WHERE characters = 'ai'
UNION ALL
SELECT id, 'boat',     'img-boat.png',     'word-boat.mp3'     FROM phonics_units WHERE characters = 'oa'
UNION ALL
SELECT id, 'toad',     'img-toad.png',     'word-toad.mp3'     FROM phonics_units WHERE characters = 'oa'
UNION ALL
SELECT id, 'tree',     'img-tree.png',     'word-tree.mp3'     FROM phonics_units WHERE characters = 'ee'
UNION ALL
SELECT id, 'bee',      'img-bee.png',      'word-bee.mp3'      FROM phonics_units WHERE characters = 'ee'
UNION ALL
SELECT id, 'cloud',    'img-cloud.png',    'word-cloud.mp3'    FROM phonics_units WHERE characters = 'ou'
UNION ALL
SELECT id, 'shout',    'img-shout.png',    'word-shout.mp3'    FROM phonics_units WHERE characters = 'ou'
UNION ALL
SELECT id, 'toy',      'img-toy.png',      'word-toy.mp3'      FROM phonics_units WHERE characters = 'oy'
UNION ALL
SELECT id, 'boy',      'img-boy.png',      'word-boy.mp3'      FROM phonics_units WHERE characters = 'oy';
