// Generated by Code Factory | Spec: SPEC-20260319-007 | Date: 2026-03-19

import { Colors, Typography, Spacing, BorderRadius, Theme, FontWeight } from '../constants/theme';

describe('Theme — Colors', () => {
  it('has a primary color', () => {
    expect(Colors.primary).toBe('#4A90D9');
  });

  it('has a secondary color', () => {
    expect(Colors.secondary).toBe('#F5A623');
  });

  it('has a background color', () => {
    expect(Colors.background).toBe('#F8F9FA');
  });

  it('has a text color', () => {
    expect(Colors.text).toBe('#1A1A2E');
  });

  it('has error and success states', () => {
    expect(Colors.error).toBeDefined();
    expect(Colors.success).toBeDefined();
  });
});

describe('Theme — Typography', () => {
  it('has sm, md, lg, xl sizes', () => {
    expect(Typography.sm).toBeDefined();
    expect(Typography.md).toBeDefined();
    expect(Typography.lg).toBeDefined();
    expect(Typography.xl).toBeDefined();
  });

  it('sm has fontSize 12', () => {
    expect(Typography.sm.fontSize).toBe(12);
  });

  it('md has fontSize 16', () => {
    expect(Typography.md.fontSize).toBe(16);
  });

  it('lg has fontSize 20', () => {
    expect(Typography.lg.fontSize).toBe(20);
  });

  it('xl has fontSize 28', () => {
    expect(Typography.xl.fontSize).toBe(28);
  });

  it('each size has lineHeight', () => {
    for (const key of Object.keys(Typography) as Array<keyof typeof Typography>) {
      expect(Typography[key].lineHeight).toBeGreaterThan(0);
    }
  });
});

describe('Theme — Spacing (8px grid)', () => {
  it('xs is 8px', () => {
    expect(Spacing.xs).toBe(8);
  });

  it('sm is 16px (2×8)', () => {
    expect(Spacing.sm).toBe(16);
  });

  it('md is 24px (3×8)', () => {
    expect(Spacing.md).toBe(24);
  });

  it('lg is 32px (4×8)', () => {
    expect(Spacing.lg).toBe(32);
  });

  it('xl is 48px (6×8)', () => {
    expect(Spacing.xl).toBe(48);
  });

  it('all spacing values are multiples of 4', () => {
    for (const key of Object.keys(Spacing) as Array<keyof typeof Spacing>) {
      expect(Spacing[key] % 4).toBe(0);
    }
  });
});

describe('Theme — BorderRadius', () => {
  it('has sm, md, lg, xl, full', () => {
    expect(BorderRadius.sm).toBeDefined();
    expect(BorderRadius.md).toBeDefined();
    expect(BorderRadius.lg).toBeDefined();
    expect(BorderRadius.xl).toBeDefined();
    expect(BorderRadius.full).toBeDefined();
  });
});

describe('Theme — FontWeight', () => {
  it('has regular, medium, semiBold, bold', () => {
    expect(FontWeight.regular).toBe('400');
    expect(FontWeight.medium).toBe('500');
    expect(FontWeight.semiBold).toBe('600');
    expect(FontWeight.bold).toBe('700');
  });
});

describe('Theme — unified export', () => {
  it('exports colors', () => {
    expect(Theme.colors).toBeDefined();
    expect(Theme.colors.primary).toBeDefined();
  });

  it('exports typography', () => {
    expect(Theme.typography).toBeDefined();
  });

  it('exports spacing', () => {
    expect(Theme.spacing).toBeDefined();
  });

  it('exports borderRadius', () => {
    expect(Theme.borderRadius).toBeDefined();
  });

  it('exports shadow', () => {
    expect(Theme.shadow).toBeDefined();
    expect(Theme.shadow.sm).toBeDefined();
    expect(Theme.shadow.md).toBeDefined();
  });
});
