// Generated by Code Factory
// Spec: SPEC-20260319-004
// Date: 2026-03-19
// DO NOT EDIT

/**
 * Shared TypeScript interfaces for the Phonics App.
 * Used by both frontend (React Native) and backend (Express API).
 * No external dependencies — pure TypeScript types only.
 */

// ─── User ────────────────────────────────────────────────────────────────────

export interface User {
  id: number;
  name: string;
  avatar: string | null;
  createdAt: Date;
}

// ─── Phonics Unit ─────────────────────────────────────────────────────────────

export type PhonicsUnitType = 'letter' | 'digraph' | 'vowelTeam';

export interface PhonicsUnit {
  id: number;
  type: PhonicsUnitType;
  /** e.g. 'a', 'sh', 'ai' */
  characters: string;
  /** e.g. 'Letter A', 'Digraph SH' */
  displayName: string;
  /** e.g. 'phoneme-a.mp3' */
  audioFile: string;
  /** Determines lesson order; ascending sort */
  orderIndex: number;
  createdAt: Date;
}

// ─── Lesson ───────────────────────────────────────────────────────────────────

export type ExerciseType = 'tap_to_hear' | 'match_sound' | 'fill_blank';

export interface Lesson {
  id: number;
  unitId: number;
  title: string;
  /** 1–5 */
  difficulty: number;
  exerciseType: ExerciseType;
  createdAt: Date;
}

// ─── Word ─────────────────────────────────────────────────────────────────────

export interface Word {
  id: number;
  unitId: number;
  word: string;
  /** Optional illustration */
  imageFile: string | null;
  /** e.g. 'word-apple.mp3' */
  audioFile: string;
  createdAt: Date;
}

// ─── User Progress ────────────────────────────────────────────────────────────

export interface UserProgress {
  id: number;
  userId: number;
  unitId: number;
  completed: boolean;
  /** 0–100 */
  score: number;
  lastAttemptedAt: Date | null;
  createdAt: Date;
}

// ─── API Response Envelope ────────────────────────────────────────────────────

export type ApiStatus = 'ok' | 'error';

export interface ApiResponse<T> {
  status: ApiStatus;
  data: T | null;
  error: string | null;
  timestamp: string; // ISO 8601
}

// ─── Request Bodies ───────────────────────────────────────────────────────────

/** Body for POST /api/progress/:userId/unit/:unitId */
export interface ProgressUpdateBody {
  completed: boolean;
  /** 0–100 */
  score: number;
}
