// Generated by Code Factory | Spec: SPEC-20260319-007 | Date: 2026-03-19
// DO NOT EDIT

/**
 * Design token system for the Phonics App.
 * Uses an 8px base grid for spacing.
 */

// ─── Colors ──────────────────────────────────────────────────────────────────

export const Colors = {
  /** Primary brand blue */
  primary: '#4A90D9',
  /** Secondary accent orange */
  secondary: '#F5A623',
  /** App background */
  background: '#F8F9FA',
  /** Primary text */
  text: '#1A1A2E',
  /** Muted text / subtitles */
  textMuted: '#6B7280',
  /** Success state */
  success: '#22C55E',
  /** Error state */
  error: '#EF4444',
  /** Warning state */
  warning: '#F59E0B',
  /** Card / surface background */
  surface: '#FFFFFF',
  /** Border / divider */
  border: '#E5E7EB',
  /** White */
  white: '#FFFFFF',
  /** Black */
  black: '#000000',
} as const;

export type ColorKey = keyof typeof Colors;

// ─── Typography ───────────────────────────────────────────────────────────────

export const Typography = {
  /** Small — captions, labels */
  sm: {
    fontSize: 12,
    lineHeight: 16,
  },
  /** Medium — body text */
  md: {
    fontSize: 16,
    lineHeight: 24,
  },
  /** Large — subheadings */
  lg: {
    fontSize: 20,
    lineHeight: 28,
  },
  /** Extra-large — headings */
  xl: {
    fontSize: 28,
    lineHeight: 36,
  },
} as const;

export type TypographyKey = keyof typeof Typography;

// ─── Font Weights ─────────────────────────────────────────────────────────────

export const FontWeight = {
  regular: '400' as const,
  medium: '500' as const,
  semiBold: '600' as const,
  bold: '700' as const,
} as const;

// ─── Spacing (8px base grid) ──────────────────────────────────────────────────

export const Spacing = {
  /** 4px */
  xxs: 4,
  /** 8px */
  xs: 8,
  /** 16px */
  sm: 16,
  /** 24px */
  md: 24,
  /** 32px */
  lg: 32,
  /** 48px */
  xl: 48,
  /** 64px */
  xxl: 64,
} as const;

export type SpacingKey = keyof typeof Spacing;

// ─── Border Radius ────────────────────────────────────────────────────────────

export const BorderRadius = {
  sm: 4,
  md: 8,
  lg: 16,
  xl: 24,
  full: 9999,
} as const;

// ─── Shadows ──────────────────────────────────────────────────────────────────

export const Shadow = {
  sm: {
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  md: {
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
} as const;

// ─── Unified Theme Export ─────────────────────────────────────────────────────

export const Theme = {
  colors: Colors,
  typography: Typography,
  fontWeight: FontWeight,
  spacing: Spacing,
  borderRadius: BorderRadius,
  shadow: Shadow,
} as const;

export type Theme = typeof Theme;
