// Generated by Code Factory | Spec: SPEC-20260319-008 | Date: 2026-03-19

/**
 * Tests for the Home screen (index.tsx).
 * All external deps (expo-router, useLessonList) are mocked.
 */

import React from 'react';
import { render, fireEvent, screen } from '@testing-library/react-native';
import HomeScreen from '../../app/index';

// ─── Mocks ────────────────────────────────────────────────────────────────────

const mockPush = jest.fn();

jest.mock('expo-router', () => ({
  useRouter: () => ({ push: mockPush }),
}));

const mockRefresh = jest.fn();

// Default hook return — overridden per test
let mockLessonHookReturn = {
  lessons: [] as import('@phonics-app/shared').Lesson[],
  isLoading: false,
  error: null as string | null,
  refresh: mockRefresh,
};

jest.mock('../../hooks/useLesson', () => ({
  useLessonList: () => mockLessonHookReturn,
  useLessonDetail: () => ({
    lesson: null,
    isLoading: false,
    error: null,
    refresh: jest.fn(),
  }),
}));

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const makeLessons = (count: number): import('@phonics-app/shared').Lesson[] =>
  Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    unitId: 1,
    title: `Lesson ${i + 1}`,
    difficulty: 1,
    exerciseType: 'tap_to_hear' as const,
    createdAt: new Date(),
  }));

// ─── Tests ────────────────────────────────────────────────────────────────────

beforeEach(() => {
  jest.clearAllMocks();
  mockLessonHookReturn = {
    lessons: [],
    isLoading: false,
    error: null,
    refresh: mockRefresh,
  };
});

describe('HomeScreen — loading state', () => {
  it('shows loading indicator when isLoading and no lessons', () => {
    mockLessonHookReturn = { ...mockLessonHookReturn, isLoading: true, lessons: [] };
    render(<HomeScreen />);
    expect(screen.getByTestId('loading-indicator')).toBeTruthy();
  });

  it('shows loading text when loading', () => {
    mockLessonHookReturn = { ...mockLessonHookReturn, isLoading: true, lessons: [] };
    render(<HomeScreen />);
    expect(screen.getByText('Loading lessons…')).toBeTruthy();
  });
});

describe('HomeScreen — error state', () => {
  it('shows error message when error is set', () => {
    mockLessonHookReturn = {
      ...mockLessonHookReturn,
      error: 'Network error',
      isLoading: false,
    };
    render(<HomeScreen />);
    expect(screen.getByText('Network error')).toBeTruthy();
  });

  it('shows retry button on error', () => {
    mockLessonHookReturn = {
      ...mockLessonHookReturn,
      error: 'Something broke',
      isLoading: false,
    };
    render(<HomeScreen />);
    expect(screen.getByTestId('retry-button')).toBeTruthy();
  });

  it('calls refresh when retry button pressed', () => {
    mockLessonHookReturn = {
      ...mockLessonHookReturn,
      error: 'Error',
      isLoading: false,
    };
    render(<HomeScreen />);
    fireEvent.press(screen.getByTestId('retry-button'));
    expect(mockRefresh).toHaveBeenCalledTimes(1);
  });
});

describe('HomeScreen — lesson list', () => {
  it('renders FlatList with lessons', () => {
    mockLessonHookReturn = {
      ...mockLessonHookReturn,
      lessons: makeLessons(3),
      isLoading: false,
    };
    render(<HomeScreen />);
    expect(screen.getByTestId('lessons-list')).toBeTruthy();
  });

  it('renders LessonCard for each lesson', () => {
    const lessons = makeLessons(2);
    mockLessonHookReturn = { ...mockLessonHookReturn, lessons };
    render(<HomeScreen />);
    expect(screen.getByTestId('lesson-card-1')).toBeTruthy();
    expect(screen.getByTestId('lesson-card-2')).toBeTruthy();
  });

  it('shows lesson titles', () => {
    mockLessonHookReturn = {
      ...mockLessonHookReturn,
      lessons: makeLessons(2),
    };
    render(<HomeScreen />);
    expect(screen.getByText('Lesson 1')).toBeTruthy();
    expect(screen.getByText('Lesson 2')).toBeTruthy();
  });
});

describe('HomeScreen — navigation', () => {
  it('navigates to lesson/[id] when card pressed', () => {
    mockLessonHookReturn = {
      ...mockLessonHookReturn,
      lessons: makeLessons(1),
    };
    render(<HomeScreen />);
    fireEvent.press(screen.getByTestId('lesson-card-1'));
    expect(mockPush).toHaveBeenCalledWith('/lesson/1');
  });

  it('navigates to /progress when progress button pressed', () => {
    mockLessonHookReturn = { ...mockLessonHookReturn, lessons: makeLessons(1) };
    render(<HomeScreen />);
    fireEvent.press(screen.getByTestId('progress-button'));
    expect(mockPush).toHaveBeenCalledWith('/progress');
  });
});

describe('HomeScreen — empty state', () => {
  it('shows empty message when no lessons and not loading', () => {
    mockLessonHookReturn = { ...mockLessonHookReturn, lessons: [], isLoading: false };
    render(<HomeScreen />);
    expect(screen.getByText('No lessons available.')).toBeTruthy();
  });
});
