// Generated by Code Factory | Spec: SPEC-20260319-010 | Date: 2026-03-19

/**
 * Tests for the Lesson Detail screen (lesson/[id].tsx).
 * All external deps are mocked.
 */

import React from 'react';
import { render, fireEvent, screen, act } from '@testing-library/react-native';
import LessonDetailScreen from '../../app/lesson/[id]';
import type { Lesson, PhonicsUnit, Word } from '@phonics-app/shared';

// ─── Mocks ────────────────────────────────────────────────────────────────────

const mockBack = jest.fn();
jest.mock('expo-router', () => ({
  useLocalSearchParams: () => ({ id: '1' }),
  useRouter: () => ({ back: mockBack }),
}));

const mockPlay = jest.fn().mockResolvedValue(undefined);
let mockAudioState = {
  play: mockPlay,
  pause: jest.fn(),
  stop: jest.fn(),
  isPlaying: false,
  isLoading: false,
  error: null as string | null,
};

jest.mock('../../hooks/useAudio', () => ({
  useAudio: () => mockAudioState,
}));

// fetch mock
const mockFetch = jest.fn();
global.fetch = mockFetch;

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const mockLesson: Lesson = {
  id: 1,
  unitId: 1,
  title: 'Letter A',
  difficulty: 1,
  exerciseType: 'tap_to_hear',
  createdAt: new Date(),
};

const mockUnit: PhonicsUnit = {
  id: 1,
  type: 'letter',
  characters: 'A',
  displayName: 'Letter A',
  audioFile: 'https://cdn.example.com/phoneme-a.mp3',
  orderIndex: 1,
  createdAt: new Date(),
};

const mockWords: Word[] = [
  {
    id: 1,
    unitId: 1,
    word: 'apple',
    imageFile: 'https://cdn.example.com/apple.jpg',
    audioFile: 'https://cdn.example.com/apple.mp3',
    createdAt: new Date(),
  },
  {
    id: 2,
    unitId: 1,
    word: 'ant',
    imageFile: null,
    audioFile: 'https://cdn.example.com/ant.mp3',
    createdAt: new Date(),
  },
];

function makeFetchResponse(data: unknown, ok = true): Response {
  return {
    ok,
    status: ok ? 200 : 404,
    statusText: ok ? 'OK' : 'Not Found',
    json: () => Promise.resolve(data),
  } as unknown as Response;
}

const successResponse = {
  status: 'ok',
  data: { lesson: mockLesson, unit: mockUnit, words: mockWords },
  error: null,
  timestamp: new Date().toISOString(),
};

// ─── Tests ────────────────────────────────────────────────────────────────────

beforeEach(() => {
  jest.clearAllMocks();
  mockAudioState = {
    play: mockPlay,
    pause: jest.fn(),
    stop: jest.fn(),
    isPlaying: false,
    isLoading: false,
    error: null,
  };
  mockFetch.mockResolvedValue(makeFetchResponse(successResponse));
});

describe('LessonDetailScreen — loading state', () => {
  it('shows loading indicator while fetching', async () => {
    // Never resolve fetch
    mockFetch.mockReturnValue(new Promise(() => undefined));
    render(<LessonDetailScreen />);
    expect(screen.getByTestId('loading-indicator')).toBeTruthy();
  });

  it('shows loading text', () => {
    mockFetch.mockReturnValue(new Promise(() => undefined));
    render(<LessonDetailScreen />);
    expect(screen.getByText('Loading lesson…')).toBeTruthy();
  });
});

describe('LessonDetailScreen — error state', () => {
  it('shows error text on fetch failure', async () => {
    mockFetch.mockRejectedValueOnce(new Error('Connection refused'));
    render(<LessonDetailScreen />);
    await screen.findByText(/Connection refused/);
  });

  it('shows back button on error', async () => {
    mockFetch.mockRejectedValueOnce(new Error('Oops'));
    render(<LessonDetailScreen />);
    await screen.findByTestId('back-button');
  });

  it('goes back when back button pressed', async () => {
    mockFetch.mockRejectedValueOnce(new Error('Oops'));
    render(<LessonDetailScreen />);
    const btn = await screen.findByTestId('back-button');
    fireEvent.press(btn);
    expect(mockBack).toHaveBeenCalledTimes(1);
  });

  it('shows error on non-ok HTTP response', async () => {
    mockFetch.mockResolvedValueOnce(makeFetchResponse({}, false));
    render(<LessonDetailScreen />);
    await screen.findByText(/HTTP 404/);
  });
});

describe('LessonDetailScreen — loaded state', () => {
  it('renders lesson title after fetch', async () => {
    render(<LessonDetailScreen />);
    await screen.findByText('Letter A');
  });

  it('renders lesson header', async () => {
    render(<LessonDetailScreen />);
    await screen.findByTestId('lesson-header');
  });

  it('renders PhonicsCard with unit characters', async () => {
    render(<LessonDetailScreen />);
    await screen.findByText('A');
  });

  it('renders phonics card play button', async () => {
    render(<LessonDetailScreen />);
    await screen.findByTestId('play-button-1');
  });

  it('renders Word Examples section', async () => {
    render(<LessonDetailScreen />);
    await screen.findByText('Word Examples');
  });

  it('renders words list', async () => {
    render(<LessonDetailScreen />);
    await screen.findByTestId('words-list');
  });

  it('renders a WordExample for each word', async () => {
    render(<LessonDetailScreen />);
    await screen.findByTestId('word-example-1');
    await screen.findByTestId('word-example-2');
  });

  it('shows word text', async () => {
    render(<LessonDetailScreen />);
    await screen.findByText('apple');
    await screen.findByText('ant');
  });
});

describe('LessonDetailScreen — audio interaction', () => {
  it('calls play when phonics card audio button pressed', async () => {
    render(<LessonDetailScreen />);
    const btn = await screen.findByTestId('play-button-1');
    await act(async () => {
      fireEvent.press(btn);
    });
    expect(mockPlay).toHaveBeenCalledWith(mockUnit.audioFile);
  });

  it('calls play when word audio button pressed', async () => {
    render(<LessonDetailScreen />);
    const btn = await screen.findByTestId('word-play-button-1');
    await act(async () => {
      fireEvent.press(btn);
    });
    expect(mockPlay).toHaveBeenCalledWith(mockWords[0]!.audioFile);
  });
});

describe('LessonDetailScreen — no words', () => {
  it('shows no-words message when words array is empty', async () => {
    mockFetch.mockResolvedValueOnce(
      makeFetchResponse({
        status: 'ok',
        data: { lesson: mockLesson, unit: mockUnit, words: [] },
        error: null,
        timestamp: new Date().toISOString(),
      }),
    );
    render(<LessonDetailScreen />);
    await screen.findByTestId('no-words');
    expect(screen.getByText('No word examples for this lesson.')).toBeTruthy();
  });
});
