// Generated by Code Factory | Spec: SPEC-20260319-011 | Date: 2026-03-19

/**
 * Tests for the Progress screen (progress.tsx).
 * expo-router and useProgress are mocked.
 */

import React from 'react';
import { render, fireEvent, screen } from '@testing-library/react-native';
import ProgressScreen from '../../app/progress';

// ─── Mocks ────────────────────────────────────────────────────────────────────

const mockPush = jest.fn();

jest.mock('expo-router', () => ({
  useRouter: () => ({ push: mockPush }),
}));

const mockRefresh = jest.fn();

let mockProgressHookReturn = {
  progress: [] as import('@phonics-app/shared').UserProgress[],
  stats: {
    totalUnits: 0,
    completedUnits: 0,
    averageScore: 0,
    completionPercent: 0,
  },
  isLoading: false,
  error: null as string | null,
  refresh: mockRefresh,
};

jest.mock('../../hooks/useProgress', () => ({
  useProgress: () => mockProgressHookReturn,
}));

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const makeProgress = (
  count: number,
  completed = true,
): import('@phonics-app/shared').UserProgress[] =>
  Array.from({ length: count }, (_, i) => ({
    id: i + 1,
    userId: 1,
    unitId: i + 1,
    completed,
    score: completed ? 80 : 0,
    lastAttemptedAt: completed ? new Date() : null,
    createdAt: new Date(),
  }));

// ─── Tests ────────────────────────────────────────────────────────────────────

beforeEach(() => {
  jest.clearAllMocks();
  mockProgressHookReturn = {
    progress: [],
    stats: { totalUnits: 0, completedUnits: 0, averageScore: 0, completionPercent: 0 },
    isLoading: false,
    error: null,
    refresh: mockRefresh,
  };
});

describe('ProgressScreen — loading state', () => {
  it('shows loading indicator when loading', () => {
    mockProgressHookReturn = { ...mockProgressHookReturn, isLoading: true };
    render(<ProgressScreen />);
    expect(screen.getByTestId('loading-indicator')).toBeTruthy();
  });

  it('shows loading text', () => {
    mockProgressHookReturn = { ...mockProgressHookReturn, isLoading: true };
    render(<ProgressScreen />);
    expect(screen.getByText('Loading progress…')).toBeTruthy();
  });
});

describe('ProgressScreen — error state', () => {
  it('shows error message', () => {
    mockProgressHookReturn = { ...mockProgressHookReturn, error: 'Server error' };
    render(<ProgressScreen />);
    expect(screen.getByText('Server error')).toBeTruthy();
  });

  it('shows retry button on error', () => {
    mockProgressHookReturn = { ...mockProgressHookReturn, error: 'Error' };
    render(<ProgressScreen />);
    expect(screen.getByTestId('retry-button')).toBeTruthy();
  });

  it('calls refresh when retry pressed', () => {
    mockProgressHookReturn = { ...mockProgressHookReturn, error: 'Error' };
    render(<ProgressScreen />);
    fireEvent.press(screen.getByTestId('retry-button'));
    expect(mockRefresh).toHaveBeenCalledTimes(1);
  });
});

describe('ProgressScreen — stats card', () => {
  it('renders stats card with heading', () => {
    render(<ProgressScreen />);
    expect(screen.getByTestId('stats-card')).toBeTruthy();
    expect(screen.getByText('Your Progress')).toBeTruthy();
  });

  it('shows completed and total units', () => {
    mockProgressHookReturn = {
      ...mockProgressHookReturn,
      progress: makeProgress(3),
      stats: {
        totalUnits: 3,
        completedUnits: 3,
        averageScore: 80,
        completionPercent: 100,
      },
    };
    render(<ProgressScreen />);
    expect(screen.getByText('3/3')).toBeTruthy();
  });

  it('shows average score', () => {
    mockProgressHookReturn = {
      ...mockProgressHookReturn,
      progress: makeProgress(2),
      stats: {
        totalUnits: 2,
        completedUnits: 2,
        averageScore: 75,
        completionPercent: 100,
      },
    };
    render(<ProgressScreen />);
    expect(screen.getByText('75%')).toBeTruthy();
  });

  it('renders progress bar', () => {
    render(<ProgressScreen />);
    expect(screen.getByTestId('progress-bar')).toBeTruthy();
  });
});

describe('ProgressScreen — badge grid', () => {
  it('renders badges-list when progress exists', () => {
    mockProgressHookReturn = {
      ...mockProgressHookReturn,
      progress: makeProgress(2),
      stats: { totalUnits: 2, completedUnits: 2, averageScore: 80, completionPercent: 100 },
    };
    render(<ProgressScreen />);
    expect(screen.getByTestId('badges-list')).toBeTruthy();
  });

  it('renders a badge for each progress entry', () => {
    mockProgressHookReturn = {
      ...mockProgressHookReturn,
      progress: makeProgress(2),
      stats: { totalUnits: 2, completedUnits: 2, averageScore: 80, completionPercent: 100 },
    };
    render(<ProgressScreen />);
    expect(screen.getByTestId('progress-badge-1')).toBeTruthy();
    expect(screen.getByTestId('progress-badge-2')).toBeTruthy();
  });

  it('shows empty state when no progress', () => {
    render(<ProgressScreen />);
    expect(screen.getByTestId('empty-state')).toBeTruthy();
    expect(screen.getByText('No progress yet. Start a lesson!')).toBeTruthy();
  });
});

describe('ProgressScreen — navigation', () => {
  it('navigates to lesson when badge pressed', () => {
    mockProgressHookReturn = {
      ...mockProgressHookReturn,
      progress: makeProgress(1),
      stats: { totalUnits: 1, completedUnits: 1, averageScore: 80, completionPercent: 100 },
    };
    render(<ProgressScreen />);
    fireEvent.press(screen.getByTestId('progress-badge-1'));
    expect(mockPush).toHaveBeenCalledWith('/lesson/1');
  });
});
