// Generated by Code Factory
// Spec: SPEC-20260319-012
// Date: 2026-03-19
// DO NOT EDIT

import { renderHook, waitFor } from '@testing-library/react-native';
import { useApi } from '../../hooks/useApi';
import type { ApiResponse } from '@phonics-app/shared';

describe('useApi Hook', () => {
  beforeEach(() => {
    global.fetch = jest.fn();
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  test('fetches and returns data on success', async () => {
    const mockData = { id: 1, name: 'Test' };
    const mockResponse: ApiResponse<typeof mockData> = {
      status: 'ok',
      data: mockData,
      error: null,
      timestamp: new Date().toISOString(),
    };

    (global.fetch as jest.Mock).mockResolvedValueOnce({
      ok: true,
      json: async () => mockResponse,
    });

    const { result } = renderHook(() => useApi<typeof mockData>('/test'));

    await waitFor(() => {
      expect(result.current.loading).toBe(false);
    });

    expect(result.current.data).toEqual(mockData);
    expect(result.current.error).toBeNull();
  });

  test('sets error on network failure', async () => {
    (global.fetch as jest.Mock).mockRejectedValueOnce(new Error('Network error'));

    const { result } = renderHook(() => useApi('/test'));

    await waitFor(() => {
      expect(result.current.loading).toBe(false);
    });

    expect(result.current.error).toBeTruthy();
    expect(result.current.data).toBeNull();
  });

  test('sets error on HTTP error response', async () => {
    (global.fetch as jest.Mock).mockResolvedValueOnce({
      ok: false,
      status: 404,
      statusText: 'Not Found',
    });

    const { result } = renderHook(() => useApi('/test'));

    await waitFor(() => {
      expect(result.current.loading).toBe(false);
    });

    expect(result.current.error).toContain('404');
  });

  test('handles API error response', async () => {
    const mockResponse: ApiResponse<null> = {
      status: 'error',
      data: null,
      error: 'Invalid request',
      timestamp: new Date().toISOString(),
    };

    (global.fetch as jest.Mock).mockResolvedValueOnce({
      ok: true,
      json: async () => mockResponse,
    });

    const { result } = renderHook(() => useApi('/test'));

    await waitFor(() => {
      expect(result.current.loading).toBe(false);
    });

    expect(result.current.error).toBe('Invalid request');
  });

  test('does not retry on POST requests', async () => {
    (global.fetch as jest.Mock).mockRejectedValueOnce(new Error('Network error'));

    const { result } = renderHook(() =>
      useApi('/test', { method: 'POST', body: { test: true } })
    );

    await waitFor(() => {
      expect(result.current.loading).toBe(false);
    });

    expect(global.fetch).toHaveBeenCalledTimes(1);
  });

  test('supports custom headers', async () => {
    const mockResponse: ApiResponse<null> = {
      status: 'ok',
      data: null,
      error: null,
      timestamp: new Date().toISOString(),
    };

    (global.fetch as jest.Mock).mockResolvedValueOnce({
      ok: true,
      json: async () => mockResponse,
    });

    renderHook(() =>
      useApi('/test', {
        headers: { Authorization: 'Bearer token' },
      })
    );

    await waitFor(() => {
      expect(global.fetch).toHaveBeenCalled();
    });

    const call = (global.fetch as jest.Mock).mock.calls[0];
    expect(call[1].headers).toHaveProperty('Authorization');
  });
});
