// Generated by Code Factory | Spec: SPEC-20260319-009 | Date: 2026-03-19

/**
 * Tests for useAudio hook.
 * expo-av is mocked so tests run in Node without a device.
 */

import { renderHook, act } from '@testing-library/react-native';
import { useAudio } from '../../hooks/useAudio';

// ─── Mocks ────────────────────────────────────────────────────────────────────

const mockUnloadAsync = jest.fn().mockResolvedValue(undefined);
const mockPauseAsync = jest.fn().mockResolvedValue(undefined);
const mockSetPositionAsync = jest.fn().mockResolvedValue(undefined);

let onStatusUpdate: ((status: object) => void) | null = null;

const mockCreateAsync = jest.fn().mockImplementation(
  (_source: unknown, _initialStatus: unknown, callback: (status: object) => void) => {
    onStatusUpdate = callback;
    return Promise.resolve({
      sound: {
        unloadAsync: mockUnloadAsync,
        pauseAsync: mockPauseAsync,
        setPositionAsync: mockSetPositionAsync,
      },
      status: { isLoaded: true, isPlaying: true },
    });
  },
);

const mockSetAudioModeAsync = jest.fn().mockResolvedValue(undefined);

jest.mock('expo-av', () => ({
  Audio: {
    Sound: {
      createAsync: (...args: unknown[]) => mockCreateAsync(...args),
    },
    setAudioModeAsync: (...args: unknown[]) => mockSetAudioModeAsync(...args),
  },
  AVPlaybackStatus: {},
}));

// ─── Tests ────────────────────────────────────────────────────────────────────

beforeEach(() => {
  jest.clearAllMocks();
  onStatusUpdate = null;
});

describe('useAudio — initial state', () => {
  it('starts with isPlaying=false, isLoading=false, error=null', () => {
    const { result } = renderHook(() => useAudio());
    expect(result.current.isPlaying).toBe(false);
    expect(result.current.isLoading).toBe(false);
    expect(result.current.error).toBeNull();
  });

  it('exposes play, pause, stop functions', () => {
    const { result } = renderHook(() => useAudio());
    expect(typeof result.current.play).toBe('function');
    expect(typeof result.current.pause).toBe('function');
    expect(typeof result.current.stop).toBe('function');
  });
});

describe('useAudio — play', () => {
  it('sets isLoading true during load, then false', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    expect(result.current.isLoading).toBe(false);
  });

  it('calls Audio.setAudioModeAsync before creating sound', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    expect(mockSetAudioModeAsync).toHaveBeenCalledTimes(1);
    expect(mockSetAudioModeAsync).toHaveBeenCalledWith(
      expect.objectContaining({ playsInSilentModeIOS: true }),
    );
  });

  it('calls Audio.Sound.createAsync with the URI', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    expect(mockCreateAsync).toHaveBeenCalledWith(
      { uri: 'https://example.com/sound.mp3' },
      { shouldPlay: true },
      expect.any(Function),
    );
  });

  it('sets isPlaying true after successful play', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    expect(result.current.isPlaying).toBe(true);
  });

  it('sets error on createAsync failure', async () => {
    mockCreateAsync.mockRejectedValueOnce(new Error('Network error'));
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    expect(result.current.error).toContain('Network error');
    expect(result.current.isPlaying).toBe(false);
  });

  it('clears previous error before new play', async () => {
    mockCreateAsync.mockRejectedValueOnce(new Error('first error'));
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    expect(result.current.error).not.toBeNull();

    await act(async () => {
      await result.current.play('https://example.com/sound2.mp3');
    });
    expect(result.current.error).toBeNull();
  });
});

describe('useAudio — pause', () => {
  it('calls pauseAsync and sets isPlaying false', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    await act(async () => {
      await result.current.pause();
    });
    expect(mockPauseAsync).toHaveBeenCalledTimes(1);
    expect(result.current.isPlaying).toBe(false);
  });

  it('does nothing if no sound loaded', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.pause();
    });
    expect(mockPauseAsync).not.toHaveBeenCalled();
  });
});

describe('useAudio — stop', () => {
  it('calls unloadAsync and sets isPlaying false', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    await act(async () => {
      await result.current.stop();
    });
    expect(mockUnloadAsync).toHaveBeenCalledTimes(1);
    expect(result.current.isPlaying).toBe(false);
  });

  it('clears error on stop', async () => {
    mockCreateAsync.mockRejectedValueOnce(new Error('load failed'));
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('bad-uri');
    });
    expect(result.current.error).not.toBeNull();
    await act(async () => {
      await result.current.stop();
    });
    expect(result.current.error).toBeNull();
  });
});

describe('useAudio — playback status callback', () => {
  it('sets isPlaying false when didJustFinish', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    act(() => {
      if (onStatusUpdate) {
        onStatusUpdate({ isLoaded: true, isPlaying: false, didJustFinish: true });
      }
    });
    expect(result.current.isPlaying).toBe(false);
  });

  it('handles unloaded status with error', async () => {
    const { result } = renderHook(() => useAudio());
    await act(async () => {
      await result.current.play('https://example.com/sound.mp3');
    });
    act(() => {
      if (onStatusUpdate) {
        onStatusUpdate({ isLoaded: false, error: 'playback failed' });
      }
    });
    expect(result.current.error).toContain('playback failed');
    expect(result.current.isPlaying).toBe(false);
  });
});
