// Generated by Code Factory | Spec: SPEC-20260319-009 | Date: 2026-03-19
// DO NOT EDIT

import { useCallback, useEffect, useRef, useState } from 'react';
import { Audio, AVPlaybackStatus } from 'expo-av';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface UseAudioReturn {
  /** Play audio from the given URI. Stops any currently playing audio first. */
  play: (uri: string) => Promise<void>;
  /** Pause currently playing audio. */
  pause: () => Promise<void>;
  /** Stop and unload currently playing audio. */
  stop: () => Promise<void>;
  /** True while audio is actively playing. */
  isPlaying: boolean;
  /** True while audio is loading / buffering. */
  isLoading: boolean;
  /** Non-null if an error occurred during load or playback. */
  error: string | null;
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

/**
 * useAudio — manages a single expo-av Sound instance.
 *
 * Usage:
 *   const { play, pause, stop, isPlaying, isLoading, error } = useAudio();
 *   await play('https://example.com/phoneme-a.mp3');
 */
export function useAudio(): UseAudioReturn {
  const soundRef = useRef<Audio.Sound | null>(null);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      void (async () => {
        if (soundRef.current !== null) {
          await soundRef.current.unloadAsync();
          soundRef.current = null;
        }
      })();
    };
  }, []);

  /**
   * Unloads current sound without resetting state.
   * Internal helper — does not touch isPlaying/isLoading.
   */
  const _unloadCurrent = useCallback(async (): Promise<void> => {
    if (soundRef.current !== null) {
      await soundRef.current.unloadAsync();
      soundRef.current = null;
    }
  }, []);

  /**
   * Playback status update handler.
   * Updates isPlaying when playback finishes or pauses.
   */
  const _onPlaybackStatusUpdate = useCallback(
    (status: AVPlaybackStatus): void => {
      if (!status.isLoaded) {
        if (status.error !== undefined) {
          setError(`Playback error: ${status.error}`);
          setIsPlaying(false);
          setIsLoading(false);
        }
        return;
      }
      setIsPlaying(status.isPlaying);
      if (status.didJustFinish) {
        setIsPlaying(false);
        // Rewind to start for potential replay
        void soundRef.current?.setPositionAsync(0);
      }
    },
    [],
  );

  const play = useCallback(
    async (uri: string): Promise<void> => {
      setError(null);
      setIsLoading(true);
      try {
        // Stop and unload any existing sound
        await _unloadCurrent();

        // Configure audio mode for playback
        await Audio.setAudioModeAsync({
          playsInSilentModeIOS: true,
          staysActiveInBackground: false,
          shouldDuckAndroid: true,
        });

        const { sound } = await Audio.Sound.createAsync(
          { uri },
          { shouldPlay: true },
          _onPlaybackStatusUpdate,
        );
        soundRef.current = sound;
        setIsPlaying(true);
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : String(err);
        setError(`Failed to load audio: ${message}`);
        setIsPlaying(false);
      } finally {
        setIsLoading(false);
      }
    },
    [_unloadCurrent, _onPlaybackStatusUpdate],
  );

  const pause = useCallback(async (): Promise<void> => {
    if (soundRef.current === null) return;
    try {
      await soundRef.current.pauseAsync();
      setIsPlaying(false);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      setError(`Failed to pause audio: ${message}`);
    }
  }, []);

  const stop = useCallback(async (): Promise<void> => {
    try {
      await _unloadCurrent();
      setIsPlaying(false);
      setError(null);
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      setError(`Failed to stop audio: ${message}`);
    }
  }, [_unloadCurrent]);

  return {
    play,
    pause,
    stop,
    isPlaying,
    isLoading,
    error,
  };
}
