// Generated by Code Factory
// Spec: SPEC-20260319-012
// Date: 2026-03-19
// DO NOT EDIT

import { useState, useCallback, useEffect } from 'react';
import type { ApiResponse } from '@phonics-app/shared';
import { API_BASE_URL, apiConfig } from '../config/api';

export interface UseApiOptions {
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
  body?: unknown;
  headers?: Record<string, string>;
}

export interface UseApiResult<T> {
  data: T | null;
  loading: boolean;
  error: string | null;
  refetch: () => Promise<void>;
}

/**
 * useApi<T>(url, options): Typed fetch wrapper with retry logic
 *
 * - Detects dev vs prod environment
 * - Retries on network failure (GET only, exponential backoff)
 * - Handles JSON parsing errors
 * - Types responses with ApiResponse<T>
 */
export function useApi<T>(
  url: string,
  options: UseApiOptions = {}
): UseApiResult<T> {
  const { method = 'GET', body, headers = {} } = options;

  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(
    async (attemptCount: number = 0): Promise<void> => {
      try {
        setLoading(true);
        setError(null);

        const fullUrl = url.startsWith('http') ? url : `${API_BASE_URL}${url}`;

        const response = await fetch(fullUrl, {
          method,
          headers: {
            'Content-Type': 'application/json',
            ...headers,
          },
          ...(body && { body: JSON.stringify(body) }),
        });

        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }

        const json = (await response.json()) as ApiResponse<T>;

        if (json.status === 'error') {
          throw new Error(json.error || 'Unknown error');
        }

        setData(json.data);
        setError(null);
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unknown error';

        // Retry only on GET requests with network errors
        if (
          method === 'GET' &&
          attemptCount < apiConfig.retryAttempts &&
          (message.includes('Network') ||
            message.includes('Failed to fetch') ||
            message.includes('timeout'))
        ) {
          const delay = apiConfig.retryDelayMs * Math.pow(2, attemptCount);
          setTimeout(() => {
            fetchData(attemptCount + 1);
          }, delay);
          return;
        }

        setError(message);
        setData(null);
      } finally {
        setLoading(false);
      }
    },
    [url, method, body, headers]
  );

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return { data, loading, error, refetch: () => fetchData() };
}
