// Generated by Code Factory | Spec: SPEC-20260319-008 | Date: 2026-03-19
// DO NOT EDIT

import { useCallback, useEffect, useState } from 'react';
import type { ApiResponse, Lesson } from '@phonics-app/shared';

// ─── Config ───────────────────────────────────────────────────────────────────

const API_BASE_URL = process.env['EXPO_PUBLIC_API_URL'] ?? 'http://localhost:3000';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface UseLessonListReturn {
  lessons: Lesson[];
  isLoading: boolean;
  error: string | null;
  refresh: () => void;
}

export interface UseLessonDetailReturn {
  lesson: Lesson | null;
  isLoading: boolean;
  error: string | null;
  refresh: () => void;
}

// ─── Hooks ────────────────────────────────────────────────────────────────────

/**
 * useLessonList — fetches GET /api/lessons and returns all lessons.
 */
export function useLessonList(): UseLessonListReturn {
  const [lessons, setLessons] = useState<Lesson[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState<number>(0);

  const refresh = useCallback(() => {
    setRefreshKey((k) => k + 1);
  }, []);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    setError(null);

    void (async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/api/lessons`);
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        const json = (await response.json()) as ApiResponse<Lesson[]>;
        if (!cancelled) {
          if (json.status === 'ok' && json.data !== null) {
            setLessons(json.data);
          } else {
            setError(json.error ?? 'Unknown error fetching lessons');
          }
        }
      } catch (err: unknown) {
        if (!cancelled) {
          const message = err instanceof Error ? err.message : String(err);
          setError(`Failed to fetch lessons: ${message}`);
        }
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [refreshKey]);

  return { lessons, isLoading, error, refresh };
}

/**
 * useLessonDetail — fetches GET /api/lessons/:id and returns a single lesson.
 */
export function useLessonDetail(id: number): UseLessonDetailReturn {
  const [lesson, setLesson] = useState<Lesson | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState<number>(0);

  const refresh = useCallback(() => {
    setRefreshKey((k) => k + 1);
  }, []);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    setError(null);

    void (async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/api/lessons/${id}`);
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        const json = (await response.json()) as ApiResponse<Lesson>;
        if (!cancelled) {
          if (json.status === 'ok' && json.data !== null) {
            setLesson(json.data);
          } else {
            setError(json.error ?? 'Unknown error fetching lesson');
          }
        }
      } catch (err: unknown) {
        if (!cancelled) {
          const message = err instanceof Error ? err.message : String(err);
          setError(`Failed to fetch lesson: ${message}`);
        }
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [id, refreshKey]);

  return { lesson, isLoading, error, refresh };
}
