// Generated by Code Factory | Spec: SPEC-20260319-011 | Date: 2026-03-19
// DO NOT EDIT

import { useCallback, useEffect, useState } from 'react';
import type { ApiResponse, UserProgress } from '@phonics-app/shared';

// ─── Config ───────────────────────────────────────────────────────────────────

const API_BASE_URL = process.env['EXPO_PUBLIC_API_URL'] ?? 'http://localhost:3000';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ProgressStats {
  totalUnits: number;
  completedUnits: number;
  averageScore: number;
  /** 0–100 */
  completionPercent: number;
}

export interface UseProgressReturn {
  progress: UserProgress[];
  stats: ProgressStats;
  isLoading: boolean;
  error: string | null;
  refresh: () => void;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function computeStats(progress: UserProgress[]): ProgressStats {
  const totalUnits = progress.length;
  const completedUnits = progress.filter((p) => p.completed).length;
  const averageScore =
    totalUnits > 0
      ? Math.round(progress.reduce((sum, p) => sum + p.score, 0) / totalUnits)
      : 0;
  const completionPercent =
    totalUnits > 0 ? Math.round((completedUnits / totalUnits) * 100) : 0;

  return { totalUnits, completedUnits, averageScore, completionPercent };
}

// ─── Hook ─────────────────────────────────────────────────────────────────────

/**
 * useProgress — fetches GET /api/progress/:userId and returns progress + stats.
 */
export function useProgress(userId: number): UseProgressReturn {
  const [progress, setProgress] = useState<UserProgress[]>([]);
  const [stats, setStats] = useState<ProgressStats>({
    totalUnits: 0,
    completedUnits: 0,
    averageScore: 0,
    completionPercent: 0,
  });
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState<number>(0);

  const refresh = useCallback(() => {
    setRefreshKey((k) => k + 1);
  }, []);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    setError(null);

    void (async () => {
      try {
        const response = await fetch(`${API_BASE_URL}/api/progress/${userId}`);
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        const json = (await response.json()) as ApiResponse<UserProgress[]>;
        if (!cancelled) {
          if (json.status === 'ok' && json.data !== null) {
            setProgress(json.data);
            setStats(computeStats(json.data));
          } else {
            setError(json.error ?? 'Unknown error fetching progress');
          }
        }
      } catch (err: unknown) {
        if (!cancelled) {
          const message = err instanceof Error ? err.message : String(err);
          setError(`Failed to fetch progress: ${message}`);
        }
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [userId, refreshKey]);

  return { progress, stats, isLoading, error, refresh };
}
