// Generated by Code Factory
// Spec: SPEC-20260319-004
// Date: 2026-03-19
// DO NOT EDIT

/**
 * Tests for shared TypeScript types.
 * Verifies interface shapes compile and properties are correct.
 * These are compile-time shape tests using TypeScript's type system.
 */

import type {
  User,
  PhonicsUnit,
  PhonicsUnitType,
  Lesson,
  ExerciseType,
  Word,
  UserProgress,
  ApiResponse,
  ProgressUpdateBody,
} from '../src/types.js';

describe('Shared TypeScript Types — shape verification', () => {
  describe('User interface', () => {
    it('should accept a valid User object', () => {
      const user: User = {
        id: 1,
        name: 'Test User',
        avatar: null,
        createdAt: new Date(),
      };
      expect(user.id).toBe(1);
      expect(user.name).toBe('Test User');
      expect(user.avatar).toBeNull();
      expect(user.createdAt).toBeInstanceOf(Date);
    });

    it('should accept a User with an avatar', () => {
      const user: User = {
        id: 2,
        name: 'Avatar User',
        avatar: 'avatar.png',
        createdAt: new Date(),
      };
      expect(user.avatar).toBe('avatar.png');
      expect(typeof user.id).toBe('number');
    });
  });

  describe('PhonicsUnit interface', () => {
    it('should accept a valid PhonicsUnit with all required fields', () => {
      const unit: PhonicsUnit = {
        id: 1,
        type: 'letter',
        characters: 'a',
        displayName: 'Letter A',
        audioFile: 'phoneme-a.mp3',
        orderIndex: 1,
        createdAt: new Date(),
      };
      expect(unit.id).toBe(1);
      expect(unit.type).toBe('letter');
      expect(unit.characters).toBe('a');
      expect(unit.displayName).toBe('Letter A');
      expect(unit.audioFile).toBe('phoneme-a.mp3');
      expect(unit.orderIndex).toBe(1);
    });

    it('should accept all valid PhonicsUnitType values', () => {
      const types: PhonicsUnitType[] = ['letter', 'digraph', 'vowelTeam'];
      expect(types).toHaveLength(3);
      expect(types).toContain('letter');
      expect(types).toContain('digraph');
      expect(types).toContain('vowelTeam');
    });

    it('should accept a digraph unit', () => {
      const unit: PhonicsUnit = {
        id: 2,
        type: 'digraph',
        characters: 'sh',
        displayName: 'Digraph SH',
        audioFile: 'phoneme-sh.mp3',
        orderIndex: 10,
        createdAt: new Date(),
      };
      expect(unit.type).toBe('digraph');
      expect(unit.characters).toBe('sh');
    });
  });

  describe('Lesson interface', () => {
    it('should accept a valid Lesson object', () => {
      const lesson: Lesson = {
        id: 1,
        unitId: 1,
        title: 'Tap to Hear: Letter A',
        difficulty: 1,
        exerciseType: 'tap_to_hear',
        createdAt: new Date(),
      };
      expect(lesson.id).toBe(1);
      expect(lesson.unitId).toBe(1);
      expect(lesson.difficulty).toBe(1);
      expect(lesson.exerciseType).toBe('tap_to_hear');
    });

    it('should accept all valid ExerciseType values', () => {
      const types: ExerciseType[] = ['tap_to_hear', 'match_sound', 'fill_blank'];
      expect(types).toHaveLength(3);
      expect(types).toContain('tap_to_hear');
      expect(types).toContain('match_sound');
      expect(types).toContain('fill_blank');
    });
  });

  describe('Word interface', () => {
    it('should accept a Word with optional imageFile null', () => {
      const word: Word = {
        id: 1,
        unitId: 1,
        word: 'apple',
        imageFile: null,
        audioFile: 'word-apple.mp3',
        createdAt: new Date(),
      };
      expect(word.word).toBe('apple');
      expect(word.imageFile).toBeNull();
      expect(word.audioFile).toBe('word-apple.mp3');
    });

    it('should accept a Word with imageFile set', () => {
      const word: Word = {
        id: 2,
        unitId: 1,
        word: 'ant',
        imageFile: 'img-ant.png',
        audioFile: 'word-ant.mp3',
        createdAt: new Date(),
      };
      expect(word.imageFile).toBe('img-ant.png');
      expect(typeof word.unitId).toBe('number');
    });
  });

  describe('UserProgress interface', () => {
    it('should accept a UserProgress with null lastAttemptedAt', () => {
      const progress: UserProgress = {
        id: 1,
        userId: 1,
        unitId: 1,
        completed: false,
        score: 0,
        lastAttemptedAt: null,
        createdAt: new Date(),
      };
      expect(progress.completed).toBe(false);
      expect(progress.score).toBe(0);
      expect(progress.lastAttemptedAt).toBeNull();
    });

    it('should accept a completed UserProgress with a timestamp', () => {
      const now = new Date();
      const progress: UserProgress = {
        id: 2,
        userId: 1,
        unitId: 2,
        completed: true,
        score: 95,
        lastAttemptedAt: now,
        createdAt: new Date(),
      };
      expect(progress.completed).toBe(true);
      expect(progress.score).toBe(95);
      expect(progress.lastAttemptedAt).toBe(now);
    });
  });

  describe('ApiResponse<T> generic interface', () => {
    it('should accept a successful ApiResponse', () => {
      const response: ApiResponse<User[]> = {
        status: 'ok',
        data: [],
        error: null,
        timestamp: new Date().toISOString(),
      };
      expect(response.status).toBe('ok');
      expect(response.data).toEqual([]);
      expect(response.error).toBeNull();
      expect(typeof response.timestamp).toBe('string');
    });

    it('should accept an error ApiResponse', () => {
      const response: ApiResponse<null> = {
        status: 'error',
        data: null,
        error: 'Not found',
        timestamp: new Date().toISOString(),
      };
      expect(response.status).toBe('error');
      expect(response.data).toBeNull();
      expect(response.error).toBe('Not found');
    });
  });

  describe('ProgressUpdateBody interface', () => {
    it('should accept a valid ProgressUpdateBody', () => {
      const body: ProgressUpdateBody = {
        completed: true,
        score: 80,
      };
      expect(body.completed).toBe(true);
      expect(body.score).toBe(80);
    });

    it('should accept a zero-score incomplete update', () => {
      const body: ProgressUpdateBody = {
        completed: false,
        score: 0,
      };
      expect(body.completed).toBe(false);
      expect(body.score).toBe(0);
    });
  });
});
