// Generated by Code Factory
// Spec: SPEC-20260319-003
// Date: 2026-03-19
// DO NOT EDIT

import { Pool, type PoolClient } from 'pg';

/**
 * PostgreSQL connection pool.
 * All connection parameters sourced from environment variables — no hardcoded values.
 *
 * Required env vars:
 *   DB_HOST     — hostname (e.g. 'db' in docker-compose, 'localhost' locally)
 *   DB_PORT     — port number (default: 5432)
 *   DB_NAME     — database name
 *   DB_USER     — database user
 *   DB_PASSWORD — database password
 */
const pool = new Pool({
  host: process.env['DB_HOST'] ?? 'localhost',
  port: Number(process.env['DB_PORT'] ?? '5432'),
  database: process.env['DB_NAME'] ?? 'phonics',
  user: process.env['DB_USER'] ?? 'postgres',
  password: process.env['DB_PASSWORD'] ?? '',
  // Pool configuration
  max: 10,
  idleTimeoutMillis: 30_000,
  connectionTimeoutMillis: 5_000,
});

pool.on('error', (err: Error) => {
  console.error('Unexpected PostgreSQL pool error:', err.message);
});

/**
 * Execute a parameterised SQL query.
 * Returns typed rows array.
 */
export async function query<T extends object = Record<string, unknown>>(
  sql: string,
  params?: unknown[]
): Promise<T[]> {
  const result = await pool.query<T>(sql, params);
  return result.rows;
}

/**
 * Acquire a client for multi-statement transactions.
 * Caller is responsible for client.release().
 */
export async function getClient(): Promise<PoolClient> {
  return pool.connect();
}

/**
 * Gracefully drain and close the connection pool.
 * Called on process shutdown.
 */
export async function closePool(): Promise<void> {
  await pool.end();
}

export default pool;
