// Generated by Code Factory
// Spec: SPEC-20260319-003
// Date: 2026-03-19
// DO NOT EDIT

import 'dotenv/config';
import express from 'express';
import { corsMiddleware } from './middleware/cors.js';
import healthRouter from './routes/health.js';
import lessonsRouter from './routes/lessons.js';
import { closePool } from './db.js';

const PORT = Number(process.env['PORT'] ?? '3001');
const HOST = '0.0.0.0'; // bind to all interfaces (required for Docker networking)

export const app = express();

// ─── Global Middleware ────────────────────────────────────────────────────────
app.use(corsMiddleware);
app.use(express.json());

// ─── Routes ───────────────────────────────────────────────────────────────────
app.use('/health', healthRouter);
app.use('/api/lessons', lessonsRouter);

// ─── 404 Handler ──────────────────────────────────────────────────────────────
app.use((_req, res) => {
  res.status(404).json({
    status: 'error',
    data: null,
    error: 'Not Found',
    timestamp: new Date().toISOString(),
  });
});

// ─── Error Handler ─────────────────────────────────────────────────────────────
app.use(
  (
    err: Error,
    _req: express.Request,
    res: express.Response,
    _next: express.NextFunction
  ) => {
    console.error('[API Error]', err.message);
    res.status(500).json({
      status: 'error',
      data: null,
      error: err.message ?? 'Internal Server Error',
      timestamp: new Date().toISOString(),
    });
  }
);

// ─── Start Server (only when not imported by tests) ──────────────────────────
let server: ReturnType<typeof app.listen> | undefined;

if (process.env['NODE_ENV'] !== 'test') {
  server = app.listen(PORT, HOST, () => {
    console.info(`[API] Server listening on http://${HOST}:${PORT}`);
  });
}

// ─── Graceful Shutdown ────────────────────────────────────────────────────────
async function shutdown(): Promise<void> {
  console.info('[API] Shutting down gracefully…');
  if (server) {
    server.close();
  }
  await closePool();
  process.exit(0);
}

process.on('SIGTERM', () => { void shutdown(); });
process.on('SIGINT',  () => { void shutdown(); });

export default app;
