// Generated by Code Factory
// Spec: SPEC-20260319-012
// Date: 2026-03-19
// DO NOT EDIT

/**
 * API Configuration
 * Detects environment and sets appropriate base URL
 */

const isProduction = process.env.NODE_ENV === 'production';

export const API_BASE_URL = isProduction
  ? '/api' // Production: relative path (nginx proxy)
  : 'http://localhost:3001'; // Development: direct to API server

export const apiConfig = {
  baseUrl: API_BASE_URL,
  timeout: 30000,
  retryAttempts: 3,
  retryDelayMs: 100,
};
